### PR TITLE
Added CSS to fix quiz label alignment, and margin correction for Twen…

### LINKED ISSUE #2132: Hello Elementor theme conflict on quiz formatting
### Reproduction Steps
1. Install LifterLMS & Hello Elementor free theme from the WordPress repository
2. Create a course with a quiz with a true/false question.
3. View the lesson and take the quiz
4. You should see the last letter goes onto a second line (screenshot below)

Screen Shot 2022-04-22 at 11 31 59 AM

### Expected Behavior
The word would be one one line

### Actual Behavior
The word is on two lines

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.9.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Blog (#2029) [[removed]/blog/]
Page On Front: Home (#1015) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.4.0
Db Version: 6.4.0
Course Catalog: Courses (#2202) [[removed]/courses/]
Membership Catalog: Membership Catalog (#2129) [[removed]/memberships/]
Student Dashboard: Dashboard (#2131) [[removed]/dashboard/]
Checkout Page: Purchase (#2130) [[removed]/purchase/]
Course Catalog Per Page: 30
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.17
Software: Apache/2.4.53 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36


Theme
-------------------------------------------

Name: Hello Elementor
Version: 2.5.0
Themeuri: https://elementor.com/hello-theme/?utm_source=wp-themes&utm_campaign=theme-uri&utm_medium=wp-dash
Authoruri: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.4.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [ ] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

### PR DESCRIPTION
**Pull request by nrherron92**
Added CSS to fix quiz label alignment, and margin correction for Twenty Twenty-Two theme, though the line may no longer be needed.

## Description
Fixes Hello Theme's word-break and spacing for quiz answer options. Also fixes text/label alignment in Twenty-Twenty-Two Theme

Fixes #2132 

## How has this been tested?
I tested it manually (after running npm run build:styles)
Tested against default twenty-nineteen, twenty-twenty, twenty twenty-one, and twenty twenty-two.
Tested also with Divi, Astra, Kadence, Elementor's Hello Theme, LaunchPad, BuddyBoss, and Page Builder Framework

## Types of changes
added: Display: block
added: margin: 0 to Twenty-Twent-Two Theme compatibility

## Checklist:
- [x] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [ ] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: includes/theme-support/class-llms-twenty-twenty-two.php [hunk 1]
```diff
@@ -92,7 +92,7 @@ protected static function generate_inline_styles( $context = null ) {
 			$styles[] = '.llms-form-field input, .llms-form-field textarea, .llms-form-field select { padding: 6px 10px }';
 
 			// Question layout.
-			$styles[] = '.llms-question-wrapper ol.llms-question-choices li.llms-choice .llms-choice-text { width: calc( 100% - 110px); }';
+			$styles[] = '.llms-question-wrapper ol.llms-question-choices li.llms-choice .llms-choice-text { width: calc( 100% - 110px); margin-top: 0; }';
```
Comment (thomasplevy) [inline includes/theme-support/class-llms-twenty-twenty-two.php]: @eri-trabiccolo a quick look at this leads me to believe that the introduction of `display:block` on the label renders this particular rule unnecessary but I'm not positive about that and didn't thoroughly test it (I manually added the added CSS via element inspector and then disabled this rule and I couldn't determine what problem this rule was trying to fix.

While we're editing this line I wanted to see if you had any thoughts on this as I believe you wrote the 2022 compat css here and might remember what conflict this rule was introduced to fix.

```suggestion
			$styles[] = '.llms-question-wrapper ol.llms-question-choices li.llms-choice .llms-choice-text { margin-top: 0; }';
```

**Comment by thomasplevy** [comment]
@nrherron92 this requires a changelog entry. Not a huge deal, but now that you're becoming a "regular" contributor it's time to learn:

On your terminal run `npm run dev changelog add -- -i` and follow the prompts to create a changelog entry to accompany the PR.

This change is a *patch*, the type is *Fixed*

Link it to the issue `#2132` and then write a concise description for the issue. Don't stress about the content of the changelog they get committed as "code" and reviewed in the changelog so that it can be reviewed alongside the actual changed code. If we (really I) don't like it, I'll make suggestions on it. Who knows what makes a good changelog entry. I certainly don't.

File: .changelogs/issue_2132.yml [hunk 2]
```diff
@@ -0,0 +1,8 @@
+significance: patch
+type: fixed
+comment: Fixes Hello Theme's word-break and spacing for quiz answer options.
+  Also fixes text/label alignment in Twenty-Twenty-Two Theme.
```
Comment (eri-trabiccolo) [inline .changelogs/issue_2132.yml]: I would swap this comment text with the entry text.
Why?
Because the comment is for internal use only while the entry is what will end-up in the actual Changelog. What you wrote here is pretty descriptive on what this PR fixes and it's perfect to be added to the Changelog for all our customers to read and immediately understand. While what you wrote as entry is more technical, it's "how" you fixed the issue, which better fits to an "internal use only" comment.

File: assets/scss/frontend/_llms-quizzes.scss [hunk 3]
```diff
@@ -165,6 +165,9 @@
 			margin: 0;
 			padding: 0;
 			position: relative;
+			label {
+				display: block;
```
Comment (eri-trabiccolo) [inline assets/scss/frontend/_llms-quizzes.scss]: just for a matter of "cleanliness" I would rather place this `display:block` in the already existent ruleset for the label:
https://github.com/gocodebox/lifterlms/blob/3c30e10802a0c3e17c5ab2b39ce1938d45be8d01/assets/scss/frontend/_llms-quizzes.scss#L211

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
Good job Natie! <3
Minor changes requested.

File: assets/scss/frontend/_llms-quizzes.scss (hunk 3 above)
Comment (nrherron92) [reply assets/scss/frontend/_llms-quizzes.scss]: Fixed!

File: .changelogs/issue_2132.yml (hunk 2 above)
Comment (nrherron92) [reply .changelogs/issue_2132.yml]: Fixed

**Review by eri-trabiccolo — APPROVED** [review]
Looks good to me. Good job @nrherron92! <3

File: includes/theme-support/class-llms-twenty-twenty-two.php (hunk 1 above)
Comment (eri-trabiccolo) [reply includes/theme-support/class-llms-twenty-twenty-two.php]: I tested the margin thing as well and find it was needed... Without it I had the label horizontally misaligned (compared to the A|B...)
Will give it another shot.
I'm now realizing this method requires a changelog and the file's `@version` would need to be changed.
I don't remember the reason for that `calc` :(

Comment (thomasplevy) [reply includes/theme-support/class-llms-twenty-twenty-two.php]: No worries we can just leave it alone. I thought it might not be needed but if you can't remember it's not hurting anyone so I say let's leave it alone.

Comment (eri-trabiccolo) [reply includes/theme-support/class-llms-twenty-twenty-two.php]: I looked into this:
- by default the label is displayed as `inline`, with no width specified.
- when so, its`.llms-choice-text` children with the width set as [width: calc(100% - 60px);](https://github.com/gocodebox/lifterlms/blob/dcc1eab319394757d69f12eade07249fa47166d3/_private/scss/frontend/_llms-quizzes.scss#L322) dropped on a new line. So I found that increasing that 60px to 110px was fine to have it back on the same line of the marker. Actually a lower value (95px) was good enough.
- Turning the label display into `block`, makes the rule `width: calc( 100% - 110px);` useless, but the `margin-top:0`; is needed.
I'm sorry but yesterday I read your comment on my mobile and didn't get what you were referring to, I thought you wanted to remove the `margin-top:0` too.


So @nrherron92, you can commit Thomas' suggestion above.

**Review by eri-trabiccolo — APPROVED** [review]
