### PR TITLE
Fix core script double registration

### LINKED ISSUE #1274: Core assets loaded with technically invalid URI
### Reproduction Steps

Seems there's a double slash in this file wp-content/plugins/lifterlms//assets/js/llms.min.js?ver=4.2.0

### Expected Behavior

Should be one /

### Actual Behavior

Double /
I also see this was fixed here: #598 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
N/A

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Home Url: https://generousmarriage.com
Site Url: https://generousmarriage.com
Login Url: https://generousmarriage.com/wp-login.php
Version: 5.4.2
Debug Mode: Yes
Debug Log: Yes
Debug Display: No
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: home (#16) [https://generousmarriage.com/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.2.0
Db Version: 4.2.0
Course Catalog: Course Catalog (#1108) [https://generousmarriage.com/courses/]
Membership Catalog: Membership Catalog (#1109) [https://generousmarriage.com/memberships/]
Student Dashboard: Dashboard (#1111) [https://generousmarriage.com/dashboard/]
Checkout Page: Purchase (#1110) [https://generousmarriage.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: hidden
Checkout Phone: hidden
Checkout Email Confirmation: no
Open Registration: no
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: hidden
Account Phone: hidden
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team@generousmarriage.com
Email From Name: The Generous Marriage Podcast
Email Footer Text:
Email Header Image:
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

PayPal: Enabled
PayPal Test Mode: Disabled
PayPal Logging: no
PayPal Order: 1
Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: no
Stripe Order: 1
Manual: Disabled
Manual Logging:
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.6.40
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 3000
Php Max Upload Size: 128 MB
Php Memory Limit: 768M
Php Post Max Size: 128M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 120
Php Version: 7.3.16
Software: Apache
Wp Memory Limit: 1024


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36


Theme
-------------------------------------------

Name: Divi Child Theme
Version:
Themeuri: https://generousmarriage.com/
Authoruri: https://generousmarriage.com/
Template: Divi
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Better Search Replace: 1.3.3
Blubrry PowerPress: 8.3.4
Classic Editor: 1.5
Embed Any Document: 2.6.1
Enable Media Replace: 3.4.1
Jetpack by WordPress.com: 8.7.1
LifterLMS: 4.2.0
LifterLMS Advanced Videos: 1.0.0-beta.8
LifterLMS Helper: 3.1.0
LifterLMS Labs: 1.5.3
LifterLMS MailChimp Add-on: 3.1.2
LifterLMS PayPal Gateway: 1.3.0
LifterLMS Stripe Payment Gateway: 5.2.0
LifterLMS WooCommerce: 2.1.1
Loco Translate: 2.4.0
Mailchimp for WooCommerce: 2.4.1
Pretty Links: 3.1.1
reSmush.it Image Optimizer: 0.3.10
SumoMe: 1.31
WooCommerce: 4.3.1
WooCommerce PayPal Checkout Gateway: 2.0.3
WooCommerce Stripe Gateway: 4.5.0
WooCommerce Subscriptions: 3.0.5
Wordfence Security: 7.4.9
WordPress Importer: 0.7
WordPress User Notes: 1.4.3
WP File Manager: 6.5
WP Rocket: 3.6.2.1
Yoast SEO: 14.6.1
Zivi Kivi: 1.0.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
WooCommerce: Yes
LifterLMS MailChimp: Yes
Videos: Vimeo: Yes
Videos: Wistia: No
Videos: YouTube: No


Template Overrides
-------------------------------------------

```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)
HS-130099

### LINKED ISSUE #1285: PHP 7.3 compat: Deprecation warning using non-string needles for str(i)pos()
### Reproduction Steps
Not sure how this can actually happen, but I could reproduce it by forcing a condition:
```
add_filter(
	'login_url',
	'__return_empty_string'
);
```

### Expected Behavior

+ No error/warning logged

### Actual Behavior

+ Deprecation warning logged

Actually the user says it happens when switched from PHP 7.3 to 7.4, but this deprecation has been introduced in 7.3
https://wiki.php.net/rfc/deprecations_php_7_3#string_search_functions_with_integer_needle

### Error Messages / Logs

```
PHP Deprecated:  stripos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /srv/www/wordpress-one/public_html/wp-content/plugins/lifterlms/includes/class.llms.ajax.php on line 130
```

### System and Environment Information
customer's one:
```

System Report:
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url:
Version: 5.4.2
Debug Mode: Yes
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#4) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.3.1
Db Version: 4.3.1
Course Catalog: Not Set
Membership Catalog: Not Set
Student Dashboard: Student Dashboard (#270) [[removed]/student-dashboard/]
Checkout Page: Not Set
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: optional
Checkout Phone: optional
Checkout Email Confirmation: no
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: optional
Account Phone: optional
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: yes
Recurring Payments: no
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image:
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: yes


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging:
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 128 MB
Php Memory Limit: 256M
Php Post Max Size: 128M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 300
Php Version: 7.4.9
Software: nginx/1.17.10
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36


Theme
-------------------------------------------

Name: MOP Divi child
Version: 1.0.0
Themeuri: https://elegantthemes.com
Authoruri:
Template: Divi
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Advanced Custom Fields: 5.8.13
AffiliateWP: 2.5.6
All In One WP Security: 4.4.4
Autocomplete WooCommerce Orders: 1.3.1
Change Quantity on Checkout for WooCommerce: 1.0
Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: 5.1.3
Cookie Notice: 1.3.2
Duplicate Page: 4.2
Easy Social Sharing: 1.3.3
ES Woocommerce ActiveCampaign: 1.9.15
Gravity Forms: 2.4.20
If Menu - Visibility control for menu items: 0.16.1
Imagify: 1.9.10
InfiniteWP - Client: 1.9.4.6
LifterLMS: 4.3.1
LifterLMS WooCommerce: 2.0.11
MOP Like Button: 1.0.0
MOP Restrict: 1.0.0
MOP User Photos: 1.0.0
PixelYourSite PRO: 7.6.1
Really Simple SSL: 3.3.4
reCaptcha for WooCommerce: 1.0.14
Redirection: 4.8
WooCommerce: 4.3.1
WooCommerce Cart Abandonment Recovery: 1.2.7
WooCommerce Checkout Field Editor: 1.5.35
WooCommerce PDF Product Vouchers: 3.7.8
WooCommerce Price Based on Country (Basic): 2.0.10
WooCommerce Stripe Gateway: 4.5.0
Woo Discount Rules: 2.0.2
WordPress Importer: 0.7
wpDiscuz: 7.0.7
WP File Manager: 6.5
WP Migrate DB Pro: 1.9.12
WP Rocket: 3.6.3
YITH WooCommerce Customize My Account Page: 2.6.4
Yoast SEO: 14.7


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
WooCommerce: Yes


Template Overrides
-------------------------------------------

content-certificate.php (ver: 3.18.0): /www/mastersofphotography_809/public/wp-content/themes/mop-divi-child/lifterlms/ (ver: 3.18.0)
course/lesson-navigation.php (ver: ): /www/mastersofphotography_809/public/wp-content/themes/mop-divi-child/lifterlms/ (ver: )
```

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information

HS-130663

### PR DESCRIPTION
**Pull request by thomasplevy**
## Description

+ Fixes #1274 
+ Fixes #1285 

## How has this been tested?

+ Manual tests

## Types of changes

+ Optimizations
+ Bug fix
+ Deprecates global js variable `window.wp_ajax_data.nonce` in favor of `window.llms.ajax_nonce`. The original seems too dangerous and ripe for a plugin/core conflict.

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by thomasplevy** [comment]
@eri-trabiccolo I based this from the work i did on #1292 so I sent this as a PR to that update. I realize that this can be done without reworking the whole asset handler but I wanted to do that.

File: assets/js/builder/Views/PostSearch.js [hunk 1]
```diff
@@ -59,11 +59,14 @@ define( [], function() {
 
 		/**
 		 * Render the section
+		 *
 		 * Initializes a new collection and views for all lessons in the section
```
Comment (eri-trabiccolo) [inline assets/js/builder/Views/PostSearch.js]:
```suggestion
		 * Initializes a new collection and views for all lessons in the section.
```

File: assets/js/builder/Views/PostSearch.js [hunk 2]
```diff
@@ -59,11 +59,14 @@ define( [], function() {
...
 		 *
-		 * @return   void
-		 * @since    3.16.0
-		 * @version  3.16.12
+		 * @since 3.16.0
+		 * @since 3.16.12 Unknown
```
Comment (eri-trabiccolo) [inline assets/js/builder/Views/PostSearch.js]:
```suggestion
		 * @since 3.16.12 Unknown.
```

File: assets/js/app/llms-ajax.js [hunk 3]
```diff
@@ -76,7 +81,7 @@ LLMS.Ajax = {
 		obj.async    = 'async'		in obj ? obj.async : this.async;
 
 		// add nonce to data object
```
Comment (eri-trabiccolo) [inline assets/js/app/llms-ajax.js]:
```suggestion
		// Add nonce to data object.
```

File: assets/js/app/llms-ajax.js [hunk 4]
```diff
@@ -58,9 +58,14 @@ LLMS.Ajax = {
...
+	 * @since Unknown
+	 * @since [version] Update ajax nonce source.
+	 *
+	 * @param {Object} obj Options object.
+	 * @return {Object}
 	 */
-	init: function(obj) {
+	init: function( obj ) {
 
 		// if obj is not of type object or null return false;
```
Comment (eri-trabiccolo) [inline assets/js/app/llms-ajax.js]:
```suggestion
		// If obj is not of type object or null return false.
```

File: assets/js/app/llms-ajax.js [hunk 5]
```diff
@@ -76,7 +81,7 @@ LLMS.Ajax = {
 		obj.async    = 'async'		in obj ? obj.async : this.async;
 
 		// add nonce to data object
-		obj.data._ajax_nonce = wp_ajax_data.nonce;
+		obj.data._ajax_nonce = window.llms.ajax_nonce || wp_ajax_data.nonce;
 
 		// add post id to data object
```
Comment (eri-trabiccolo) [inline assets/js/app/llms-ajax.js]:
```suggestion
		// Add post id to data object.
```

File: assets/js/llms-admin.js [hunk 6]
```diff
@@ -163,11 +164,13 @@
...
-	 *                          each default option will pulled from the elements data-attributes
-	 * @return   void
-	 * @since    ??
-	 * @version  3.17.5
+	 *
+	 * @since Unknown
+	 * @since 3.17.5 Unknown.
+	 * @since [version] Update ajax nonce source.
+	 *
+	 * @param obj options Options passed to Select2. Each default option will pulled from the elements data-attributes.
```
Comment (eri-trabiccolo) [inline assets/js/llms-admin.js]:
```suggestion
	 * @param obj options Options passed to Select2. Each default option will be pulled from the elements data-attributes.
```

File: includes/admin/class.llms.admin.assets.php [hunk 7]
```diff
@@ -252,9 +255,11 @@ public function admin_scripts() {
 	/**
 	 * Initialize the "llms" object for other scripts to hook into
 	 *
+	 * @since 1.0.0
+	 * @since 3.7.5 Unknown
```
Comment (eri-trabiccolo) [inline includes/admin/class.llms.admin.assets.php]:
```suggestion
	 * @since 3.7.5 Unknown.
```

File: includes/class.llms.frontend.assets.php [hunk 8]
```diff
@@ -205,6 +204,10 @@ public static function enqueue_scripts() {
 			'llms-ajaxurl',
 			'window.llms = window.llms || {};window.llms.ajaxurl = "' . admin_url( 'admin-ajax.php', $ssl ) . '";'
 		);
+		self::enqueue_inline_script(
```
Comment (eri-trabiccolo) [inline includes/class.llms.frontend.assets.php:207]: the static method `enqueue_inline_script` could be moved - and slightly modified - (of course for bw compatibility we'll maintain a wrapper here) into `LLMS_Assets`... what do you think?

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
Look except for the minor changes we have a bigger issue here.
I tested it with some add-ons active, e.g. the Advanced Videos, and got this in the builder:
```
llms-av-builder.js?ver=1.0.0-beta.11:38 Uncaught TypeError: LLMS.l10n.translate is not a function
    at new AV_Builder (llms-av-builder.js?ver=1.0.0-beta.11:38)
    at llms-av-builder.js?ver=1.0.0-beta.11:437
    at llms-av-builder.js?ver=1.0.0-beta.11:440
```
you can guess why: av-builder.js enqueued before llms.js
https://github.com/gocodebox/lifterlms-advanced-videos/blob/1.0.0-beta.11/includes/class-llms-av-assets.php#L30

We should be able to fix this, without introducing any other issue, by requiring the 'llms' script as dep here:
https://github.com/gocodebox/lifterlms-advanced-videos/blob/1.0.0-beta.11/includes/class-llms-av-assets.php#L95
(from a rapid test it does the job)
But this means we have to raise the core min required version in the av addon, and release a new version before the core.

But we should carefully check the other add-ons too.

File: includes/class.llms.frontend.assets.php (hunk 8 above)
Comment (thomasplevy) [reply includes/class.llms.frontend.assets.php:207]: I was thinking about this too... All the inline stuff could be it's own class. I was thinking about making an `LLMS_Assets_Inline` class in favor of adding the inline stuff to the assets class. Actually, maybe it would make more sense to make inline asset-related functionality a trait that gets mixed into the asset class. I'm thinking mostly of keeping the number of methods per file smaller.

What do you think?

Comment (thomasplevy) [reply includes/class.llms.frontend.assets.php:207]: I'm going to move this conversation into #1292 so I can merge this into that PR

Comment (eri-trabiccolo) [reply includes/class.llms.frontend.assets.php:207]: You know I'm not sure what this LLMS_Assets_Inline would do.
Not sure if semantically it makes sense making a class for that, I understand keeping the number of methods per file smaller though.
Traits can be good, but you know we'll only use them here. 
Will the Inline stuff add so many methods?
