### PR TITLE
handle undefined return from `wp.data.select( ... )` when both Yoast …

### LINKED ISSUE #2298: Yoast/Classic Editor/LifterLMS Javascript Error Combo
### Reproduction Steps

+ HS-208526
+ As far as I can tell this doesn't break anything or prevent you from doing anything on the site, but I guess could cause server issues eventually. 

Requirements:

    WordPress: 6.1
    LifterLMS: 7.0
    Classic Editor: 1.6.2
    Yoast SEO: 19.10

Steps to reproduce:

+ With the latest versions of LifterLMS, Classic Editor, and Yoast plugins installed on WordPress 6.1, go to any post single edit screen
+ Open the browser console
+ See error messages constantly generated (due to infinite loop/interval)

### Expected Behavior

+ No Javascript Issues

### Actual Behavior

+ An infinite loop

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->
Uncaught TypeError: can't access property "getMetaBoxesPerLocation", wp.data.select(...) is undefined
    bind_mce_fixes llms-metaboxes.js:1285
    i llms.js:2545
97 [llms-metaboxes.js:1285](https://natie.myliftersite.com/wp-content/plugins/lifterlms/assets/js/llms-metaboxes.js)
    bind_mce_fixes llms-metaboxes.js:1285
    i llms.js:2545

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natie.myliftersite.com
Site Url: https://natie.myliftersite.com
Login Url: https://natie.myliftersite.com/wp-login.php
Version: 6.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 7.0.0
Db Version: 7.0.0
Course Catalog: Course Catalog (#120) [https://natie.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#121) [https://natie.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#123) [https://natie.myliftersite.com/dashboard/]
Checkout Page: Purchase (#122) [https://natie.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+trial@lifterlms.com
Email From Name: My LifterLMS Trial Site
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 
Cert Bg Height: 
Cert Legacy Compat: 


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.40
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.25
Software: Apache/2.4.54 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0


Theme
-------------------------------------------

Name: Divi
Version: 4.19.0
Themeuri: http://www.elegantthemes.com/gallery/divi/
Authoruri: http://www.elegantthemes.com
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

Classic Editor: 1.6.2
LifterLMS: 7.0.0
Yoast SEO: 19.10


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Firefox, MacOS Monterey 12.5.1

### PR DESCRIPTION
**Pull request by thomasplevy**
…and Classic Ed plugins are installed

## Description

Fixes #2298 

## How has this been tested?
+ Manually

## Types of changes
Bugfix

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: assets/js/llms-metaboxes.js [hunk 1]
```diff
@@ -1276,16 +1276,19 @@
 		 * Re-initializes TinyMCE Editors found within metaboxes
 		 *
 		 * @since 4.19.0
```
Comment (nrherron92) [inline assets/js/llms-metaboxes.js:1278]: added twice, one should be removed

File: assets/js/private/llms-metaboxes.js [hunk 2]
```diff
@@ -775,16 +775,19 @@
 		 * Re-initializes TinyMCE Editors found within metaboxes
 		 *
 		 * @since 4.19.0
+		 * @since 4.19.0
```
Comment (nrherron92) [inline assets/js/private/llms-metaboxes.js]: added twice

**Review by nrherron92 — CHANGES_REQUESTED** [review]

**Review by nrherron92 — APPROVED** [review]
Looks good!
