### PR TITLE
Fix deleting membership enrollment doesn't delete related courses aut…

### LINKED ISSUE #952: Deleting membership enrollment doesn't delete related courses auto-enrollments.
### Reproduction Steps

+ Create two courses and a membership.
+ Set the membership auto enrollment so that who enrolls the membership automatically enrolls the two courses too.
+ from the Student Management meta box, still in the membership edit screen, enroll a student
+ The student will be auto-enrolled to the two courses above (verify it)
+ Now from the same Student Management meta box, still in the membership edit screen, unenroll a student (click on the x), then remove it (click on the trash icon).
+ The membership enrollment record is deleted from the DB, and you cannot see the student in the table anymore, and that's fine.

### Expected Behavior
 
+ The student enrollments data related to the two courses above, that have been automatically created, should be automatically removed too, so, e.g. when checking the enrolled students table in one of those course's edit screen I will not see the student's enrollment related to the one I deleted in the membership screen.

### Actual Behavior

+ When checking the enrolled students table in one of those course's edit screen I STILL see the student's enrollment related to the one I deleted in the membership screen: the course auto-enrollment data has been not deleted.

I think that when deleting an enrollment we should mimic a little more the [unenrollment method](https://github.com/gocodebox/lifterlms/blob/3.36.1/includes/models/model.llms.student.php#L1565), so my idea is to call the method `LLMS_Student->remove_membership_level()` in 
the [delete_enrollment](https://github.com/gocodebox/lifterlms/blob/3.36.1/includes/models/model.llms.student.php#L1632) method too, but passing to this an additional parameter `$delete=true`.
`LLMS_Student->remove_membership_level()` when this parameter is set to `true` instead of doing:
https://github.com/gocodebox/lifterlms/blob/3.36.1/includes/models/model.llms.student.php#L1496
will do:
`$this->delete_enrollment( $course_id, 'membership_' . $membership_id );`
Alternatively we can use the already present `$status` param for this purpose, and doing what said above e.g. when it is set to `deleted`.
We could simplify things and just run a "deletion query" but I don't want to loose actions or caches set ecc.

### Error Messages / Logs

n/a

### System Information

LifterLMS 3.36.1 (but this issue is there since the introduction of the delete enrollment feature in v3.33.0)

### Browser, Device, and Operating System Information

n/a

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
…o-enrollments

Fixes #952
Fixes https://github.com/gocodebox/lifterlms-rest/issues/95

## Description
Added logic to physically remove from the membership level and remove enrollments data on related products, when deleting a membership enrollment.

## How has this been tested?
manually, by deleting enrollments from membership screen, and through existing and new unit tests

## Types of changes
Bug fix

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests.
- [x] My code follows the LifterLMS Coding Standards.

### CODE REVIEW

File: tests/unit-tests/user/class-llms-test-student.php [hunk 1]
```diff
@@ -519,11 +540,28 @@ public function test_is_enrolled() {
 		$this->assertFalse( $student->is_enrolled( $courses, 'any' ) );
 		$this->assertFalse( $student->is_enrolled( $courses, 'all' ) );
 
-		// deleted
+		// deleted.
```
Comment (thomasplevy) [inline tests/unit-tests/user/class-llms-test-student.php]: thanks <3 (not sarcastic)
