### PR TITLE
Fx checkout broken on Twenty Twenty Two Theme

### LINKED ISSUE #1997: Checkout broken on Twenty Twenty Two Theme
### Reproduction Steps

+ Load the checkout screen using the 2022 theme
+ Observe the JS errors in the console

```
llms-form-checkout.js?ver=5.9.0:65 Uncaught TypeError: Cannot read properties of undefined (reading 'checkout')
    at llms_checkout.init (llms-form-checkout.js?ver=5.9.0:65:38)
    at new llms_checkout (llms-form-checkout.js?ver=5.9.0:568:8)
    at llms-form-checkout.js?ver=5.9.0:575:25
    at llms-form-checkout.js?ver=5.9.0:577:4
init @ llms-form-checkout.js?ver=5.9.0:65
llms_checkout @ llms-form-checkout.js?ver=5.9.0:568
(anonymous) @ llms-form-checkout.js?ver=5.9.0:575
(anonymous) @ llms-form-checkout.js?ver=5.9.0:577
llms-stripe.js?ver=5.4.0:388 Uncaught TypeError: Cannot read properties of undefined (reading 'add_gateway')
    at llms-stripe.js?ver=5.4.0:388:23
    at llms-stripe.js?ver=5.4.0:392:2
```

### Notes

This, I think, is a change in how FSE themes handle asset enqueue... On this line we conditionally enqueue the PW strength meter JS: https://github.com/gocodebox/lifterlms/blob/trunk/includes/forms/class-llms-form-field.php#L788

But this line never runs because on the theme scripts haven't been enqueued when the HTML is parsed? I guess maybe there's a pre-parse that happens with FSE and these php templates or something? I'm not sure.. I haven't investigate thorougly.

A simple fix may be to remove this conditional and just define the pw strength meter script as a dependency of the checkout script and always localize with the PW strength meter stuff. This is a small performance hit for those not using the PW strength meter but it's a less convoluted way of defining the dependencies. And my guess is we wouldn't encounter this issue if we did it this way regardless of what's going on in the theme (or maybe FSE themes in general??)

---

Edit: The stripe issue is irrelevant because the checkout script never fully initializes because of the initial error. I included it for thoroughness though.

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description
Fixes #1997 

## How has this been tested?
manually (with 2022 and Astra themes) and already existing unit tests

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: includes/forms/class-llms-form-field.php [hunk 1]
```diff
@@ -784,21 +785,47 @@ protected function prepare_password_strength_meter() {
...
+	 * @param array $meter_settings {
+	 *     Hash of meter configuration options.
+	 *
+	 *     @type string[] $blocklist    A list of strings that are penalized when used in the password. See "user_inputs" at https://github.com/dropbox/zxcvbn#usage.
+	 *     @type string   $min_strength The minimum acceptable password strength. Accepts "strong", "medium", or "weak". Default: "strong".
+	 *     @type int      $min_length   The minimum acceptable password length. Must be >= 6. Default: 6.
+	 * }
+	 * @return void
+	 */
+	public function enqueue_strength_meter( $meter_settings ) {
```
Comment (thomasplevy) [inline includes/forms/class-llms-form-field.php]:
```suggestion
	private function enqueue_strength_meter( $meter_settings ) {
```

Sometimes you disgust me.

File: includes/forms/class-llms-form-field.php [hunk 2]
```diff
@@ -784,21 +785,47 @@ protected function prepare_password_strength_meter() {
...
-				'window.LLMS.PasswordStrength = window.LLMS.PasswordStrength || {};window.LLMS.PasswordStrength.get_settings = function() { return JSON.parse( \'' . wp_json_encode( $meter_settings ) . '\' ); };',
-				'footer',
-				15
+			$this->enqueue_strength_meter( $meter_settings );
+		} else { // Otherwise add it whe `wp_enqueue_scripts` is fired.
+			add_action(
+				'wp_enqueue_scripts',
+				function() use ( $meter_settings ) {
+					$this->enqueue_strength_meter( $meter_settings );
+				}
```
Comment (thomasplevy) [inline includes/forms/class-llms-form-field.php]: This can cut down on the else condition.

```suggestion
			return $this->enqueue_strength_meter( $meter_settings );
		}
		// Otherwise add it whe `wp_enqueue_scripts` is fired.
		add_action(
			'wp_enqueue_scripts',
			function() use ( $meter_settings ) {
				$this->enqueue_strength_meter( $meter_settings );
			}
```

**Review by thomasplevy — CHANGES_REQUESTED** [review]
This is an elegant solution. A few minor changes and then the test at https://github.com/gocodebox/lifterlms/blob/d52e8861662efe9d79daf57294293cf14acb065b/tests/phpunit/unit-tests/forms/class-llms-test-form-field.php#L936-L952 should be updated to test both enqueue conditions.

File: includes/forms/class-llms-form-field.php (hunk 1 above)
Comment (eri-trabiccolo) [reply includes/forms/class-llms-form-field.php]: oh yeah that's because at first I thought at that as a hook callback <3

Comment (thomasplevy) [reply includes/forms/class-llms-form-field.php]: Yea i figured

**Review by thomasplevy — APPROVED** [review]
