### PR TITLE
Fix checkout form with no (visible) fields and always require email fields in checkout/registration

### LINKED ISSUE #1607: [5.x] A checkout form with no (visible) fields is weird
### Reproduction Steps

+ Create a checkout form with only an email and password field
+ Set the visibility value of both fields to "logged out"
+ View the checkout form as logged in user

### Expected Behavior

+ I'm not entirely sure

### Actual Behavior

+ It looks weird

Screenshot_2021-04-21_09-22-22

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description
Fixes #1607 
Partial fix for #1589 (Only requires email address for checkout/registration fields).

## How has this been tested?
manually and with old and new unit tests (missing tests on the new `is_block_visible_in_list()`)

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: includes/forms/class-llms-forms.php [hunk 1]
```diff
@@ -130,10 +132,23 @@ public function are_usernames_enabled() {
 	 */
 	private function block_to_field_settings( $block ) {
 
+		$is_visible = $this->is_block_visible( $block );
+		/**
+		 * Filters whether or not invisible fields should be included
+		 *
+		 * If the block is not visible (according to LLMS block-level visibility settings)
+		 * it will return an empty array (signaling the field to be removed).
+		 *
```
Comment (thomasplevy) [inline includes/forms/class-llms-forms.php:143]:
```suggestion
		 *
		 * @since [version]
		 *
```

File: includes/forms/class-llms-forms.php [hunk 2]
```diff
@@ -130,10 +132,23 @@ public function are_usernames_enabled() {
...
+		 * @param $filter Whether or not invisible fields should be included. Default is `false`.
+		 */
+		if ( ! $is_visible && apply_filters( 'llms_filter_out_invisible_field', false ) ) {
```
Comment (thomasplevy) [inline includes/forms/class-llms-forms.php]: "filter_out" feels programmy and "hide" seems to be more readibly understandable... I think?

Also, prefixing the filter with "forms" like many of the other hooks in this area of the codebase seems to make it less prone to future collisions.

```suggestion
		if ( ! $is_visible && apply_filters( 'llms_forms_remove_invisible_field', false ) ) {
```

File: includes/forms/class-llms-form-handler.php [hunk 3]
```diff
@@ -319,8 +319,11 @@ public function submit( $posted_data, $location, $args = array() ) {
 		// Determine the user action to perform.
 		$action = get_current_user_id() ? 'update' : 'registration';
 
-		// Load the form.
+		// Load the form, filtering out invisible fields.
+		add_filter( 'llms_filter_out_invisible_field', '__return_true', 999 );
```
Comment (thomasplevy) [inline includes/forms/class-llms-form-handler.php]: Change explained below.

```suggestion
		add_filter( 'llms_forms_remove_invisible_field', '__return_true', 999 );
```

File: includes/forms/class-llms-form-handler.php [hunk 4]
```diff
@@ -319,8 +319,11 @@ public function submit( $posted_data, $location, $args = array() ) {
...
 		$fields = $this->get_fields( $action, $location, $args );
+		remove_filter( 'llms_filter_out_invisible_field', '__return_true', 999 );
```
Comment (thomasplevy) [inline includes/forms/class-llms-form-handler.php]: Change explained below

```suggestion
		remove_filter( 'llms_forms_remove_invisible_field', '__return_true', 999 );
```

File: includes/forms/class-llms-form-handler.php [hunk 5]
```diff
@@ -319,8 +319,11 @@ public function submit( $posted_data, $location, $args = array() ) {
 		// Determine the user action to perform.
 		$action = get_current_user_id() ? 'update' : 'registration';
 
-		// Load the form.
+		// Load the form, filtering out invisible fields.
```
Comment (thomasplevy) [inline includes/forms/class-llms-form-handler.php]: Method needs a version doc

File: includes/forms/class-llms-form-handler.php [hunk 6]
```diff
@@ -333,6 +336,7 @@ public function submit( $posted_data, $location, $args = array() ) {
 	}
 
 	/**
+	 * Form fields submission
```
Comment (thomasplevy) [inline includes/forms/class-llms-form-handler.php:357]: File needs version doc

File: includes/forms/class-llms-forms.php [hunk 7]
```diff
@@ -64,6 +65,7 @@ private function __construct() {
 		add_filter( 'render_block', array( $this, 'render_field_block' ), 10, 2 );
 		add_filter( 'llms_get_form_post', array( $this, 'maybe_load_preview' ) );
 
+		add_filter( 'llms_get_form_blocks', array( $this, 'maybe_add_required_email_field_block' ), 999, 3 );
```
Comment (thomasplevy) [inline includes/forms/class-llms-forms.php]: I think this hook & method should be moved to the `LLMS_Forms_Dynamic_Fields` class

File: includes/forms/class-llms-form-templates.php [hunk 8]
```diff
@@ -121,13 +121,14 @@ private static function find_reusable_block( $field_id ) {
 	 * block modified by legacy options for the given location when `$reusable` is `false`.
 	 *
 	 * @since 5.0.0
+	 * @since [version] Method access set to public.
```
Comment (thomasplevy) [inline includes/forms/class-llms-form-templates.php:125]: file needs version update

File: includes/forms/class-llms-form-validator.php [hunk 9]
```diff
@@ -376,14 +376,15 @@ protected function validate_field_voucher( $posted_value ) {
 	 * Validate submitted field values.
 	 *
 	 * @since 5.0.0
+	 * @since [version] Don't validate form with no user input only if the form is not empty itself (e.g. contains only invisible fields).
```
Comment (thomasplevy) [inline includes/forms/class-llms-form-validator.php:379]: file needs version update

File: includes/forms/class-llms-forms.php [hunk 10]
```diff
@@ -1002,6 +1019,37 @@ public function render_field_block( $html, $block ) {
...
+	 * @param array   $args     Additional arguments passed to the short-circuit filter.
+	 * @return array[]
+	 */
+	public function maybe_add_required_email_field_block( $blocks, $location, $args ) {
+
+		if ( is_user_logged_in() || ! in_array( $location, array( 'checkout', 'registration' ), true ) ) {
+			return $blocks;
+		}
+
+		foreach ( $this->get_field_blocks( $blocks ) as $field_block ) {
```
Comment (thomasplevy) [inline includes/forms/class-llms-forms.php]: We can use `LLMS_Forms::get_field_by( ... )` to pull the email field out of the form by its id and then check if the block is visible. If it returns false, add the field.

If it returns the field and the block isn't visible we should modify the visibility settings to make it visible instead of adding a new field dynamically. My thinking on this is that if someone has made customizations to the email address field (label, description, etc...) we want to ensure those still hold

**Review by thomasplevy — CHANGES_REQUESTED** [review]

File: includes/shortcodes/class.llms.shortcode.checkout.php [hunk 11]
```diff
@@ -291,9 +292,27 @@ protected static function setup_plan_and_form_atts( $plan_id, $atts ) {
...
 
+	/**
+	 * Clean form fields html
+	 *
+	 * Properly detects empty form fields when the html is only composed of blanks and empty paragraphs.
+	 * In this case the form fields html is turned into an empty string.
+	 *
+	 * @since [version]
+	 *
+	 * @param array $fields Form Fields.
```
Comment (thomasplevy) [inline includes/shortcodes/class.llms.shortcode.checkout.php]:
```suggestion
	 * @param array $fields_html Form Fields.
```

**Review by thomasplevy — CHANGES_REQUESTED** [review]

File: includes/forms/class-llms-form-templates.php (hunk 8 above)
Comment (eri-trabiccolo) [reply includes/forms/class-llms-form-templates.php:125]: jeez

File: includes/forms/class-llms-forms.php (hunk 7 above)
Comment (eri-trabiccolo) [reply includes/forms/class-llms-forms.php]: not as it is right now, because I need $this->is_block_visible()

File: includes/forms/class-llms-forms.php (hunk 2 above)
Comment (eri-trabiccolo) [reply includes/forms/class-llms-forms.php]: we decided to name it `'llms_forms_remove_invisible_field'`

File: includes/forms/class-llms-forms.php (hunk 10 above)
Comment (eri-trabiccolo) [reply includes/forms/class-llms-forms.php]: I see what you mean, yeah

File: includes/forms/class-llms-forms.php (hunk 2 above)
Comment (thomasplevy) [reply includes/forms/class-llms-forms.php]: I missed it

File: includes/forms/class-llms-forms.php (hunk 7 above)
Comment (thomasplevy) [reply includes/forms/class-llms-forms.php]: mmmm okay... well i think to keep the "dynamic" stuff in a single class makes sense... Make the method public then!

Comment (eri-trabiccolo) [reply includes/forms/class-llms-forms.php]: ok

File: includes/forms/class-llms-forms.php (hunk 2 above)
Comment (thomasplevy) [reply includes/forms/class-llms-forms.php]: Fixed review :arrow_up:

File: includes/forms/class-llms-forms.php (hunk 10 above)
Comment (eri-trabiccolo) [reply includes/forms/class-llms-forms.php]: @thomasplevy 
what do you think about the invisible fields handling strategy in https://github.com/gocodebox/lifterlms/pull/1688/commits/7379f4ba582059c90ae560783edc6fbfc96752a7

File: includes/forms/class-llms-forms.php [hunk 12]
```diff
@@ -816,6 +847,91 @@ private function is_block_visible( $block ) {
...
+
+	/**
+	 * Returns a list of block parents plus the block itself in reverse order
+	 *
+	 * @since [version]
+	 *
+	 * @param array   $block      Parsed block array.
+	 * @param array[] $block_list The list of WP Block array `$block` comes from.
+	 * @param int     $iterations Stores the number of iterations.
+	 * @return bool
```
Comment (thomasplevy) [inline includes/forms/class-llms-forms.php:896]:
```suggestion
	 * @return array[] List of WP_Block arrays describing or an empty array if $block cannot be found within $block_list
```

File: includes/forms/class-llms-forms.php [hunk 13]
```diff
@@ -816,6 +847,91 @@ private function is_block_visible( $block ) {
...
+						}
+
+						// Merge.
+						return array_merge( $path, $to_merge );
+					}
+				}
+			}
+		}
+
+		return false;
```
Comment (thomasplevy) [inline includes/forms/class-llms-forms.php]:
```suggestion
		return array();
```

I've found a way to break this (cause a fatal error attempting to run `false` into `foreach()`) by passing in a `$block_list` that does not contain `$block` which technically shouldn't happen unless custom code uses this incorrectly *but* if we return `array()` in favor of false it works exactly as expected and `is_block_visible_in_list()` will return false, which I think would be the semantically correct response: the block isn't in the list so it cannot logically be visible within the list...

File: includes/forms/class-llms-forms.php (hunk 12 above)
Comment (thomasplevy) [inline includes/forms/class-llms-forms.php]: Incorrect return

```suggestion
	 * @return array[] List of WP_Block arrays describing or an empty array if $block cannot be found within $block_list
```

**Review by thomasplevy — CHANGES_REQUESTED** [review]
Overall I think that while the `get_block_path()` method is not the most appealing piece of code ever written it *seems to work*

I couldn't handle reading it alone and then manually testing all the conditions so I wrote a set of tests to test `get_block_path()` and `is_block_visible_in_list()` which I believe cover every possible condition we care about...

I've also made some changes to reduce code complexity as reported by codeclimate and make it a little easier to read (in my opinion, at least)

I haven't thoroughly reviewed the dynamic email/password functionality yet. I'll be doing that next

**Comment by thomasplevy** [comment]
See https://github.com/eri-trabiccolo/lifterlms/pull/2

File: includes/forms/class-llms-forms-dynamic-fields.php [hunk 14]
```diff
@@ -209,6 +210,151 @@ public function modify_account_form( $blocks, $location ) {
...
+		 * Filters the required block fields to add to the form
+		 *
+		 * @since [version]
+		 *
+		 * @param array[] $fields   Array of field_id => block_name required.
+		 * @param array[] $blocks   Array of parsed WP_Block arrays.
+		 * @param string  $location The request form location ID.
+		 * @param array   $args     Additional arguments passed to the short-circuit filter.
+		 */
+		$fields_to_require = apply_filters( 'llms_forms_required_block_fields', $fields_to_require, $blocks, $location, $args );
```
Comment (thomasplevy) [inline includes/forms/class-llms-forms-dynamic-fields.php]: Reduce method size by moving this to another method

File: includes/forms/class-llms-forms-dynamic-fields.php [hunk 15]
```diff
@@ -209,6 +210,151 @@ public function modify_account_form( $blocks, $location ) {
...
+				unset( $fields_to_require[ $field_id ] );
+				if ( empty( $fields_to_require ) ) { // All the required blocks are present.
+					return $blocks;
+				}
+			}
+		}
+
+		$blocks_to_add = array();
+		foreach ( $fields_to_require as $field_id => $block_to_add ) {
+			$blocks_to_add[] = LLMS_Form_Templates::get_block( $block_to_add, $location, true );
```
Comment (thomasplevy) [inline includes/forms/class-llms-forms-dynamic-fields.php]: I think that *if* the reusable block exists it should be used here but if it *doesn't* exist it will be created on the page load (and then used again later)

And this just doens't feel like the proper way to handle this to me although it does make it more possible for users to customize the field.

The *best* scenario I think would be to lookup if the reusable exists and then use it if it does and use a non-reusable if it doesn't but 

Modified some things on my PR, thoughts?

**Review by thomasplevy — CHANGES_REQUESTED** [review]

File: includes/forms/class-llms-forms-dynamic-fields.php (hunk 15 above)
Comment (eri-trabiccolo) [reply includes/forms/class-llms-forms-dynamic-fields.php]: @thomasplevy 
All you say makes sense. And all I see in your PR makes sense too. I could just merge it now, what do you think? Then I'll give it a better review tomorrow.

**Comment by thomasplevy** [comment]
@eri-trabiccolo with my changes on your fork at https://github.com/eri-trabiccolo/lifterlms/pull/2 I'm very happy with this. I've tested most of the scenarios manually and I think if you could take a review at my changes / suggestions on your fork and merge that in this PR is probably pretty good to ship.

**Comment by thomasplevy** [comment]
Man this was a tough one...

File: includes/forms/class-llms-forms.php [hunk 16]
```diff
@@ -816,6 +847,102 @@ private function is_block_visible( $block ) {
...
+
+	/**
+	 * Returns a list of block parents plus the block itself in reverse order
+	 *
+	 * @since [version]
+	 *
+	 * @param array   $block      Parsed block array.
+	 * @param array[] $block_list The list of WP Block array `$block` comes from.
+	 * @param int     $iterations Stores the number of iterations.
+	 * @return array[] List of WP_Block arrays describing or an empty array if $block cannot be found within $block_list
```
Comment (thomasplevy) [inline includes/forms/class-llms-forms.php]:
```suggestion
	 * @return array[] List of WP_Block arrays or an empty array if $block cannot be found within $block_list
```

File: tests/phpunit/unit-tests/forms/class-llms-test-form-handler.php [hunk 17]
```diff
@@ -324,11 +325,85 @@ public function test_submit_success() {
...
 
+
+	/**
+	 * Test submit password change without providing, or with wrong current password
+	 *
+	 * @since [version]
+	 *
+	 * @return void
+	 */
+	public function test_submit_password_update_wrong_current_password() {
```
Comment (thomasplevy) [inline tests/phpunit/unit-tests/forms/class-llms-test-form-handler.php:343]: I think this test and the next test have transposed names/descriptions

Comment (eri-trabiccolo) [reply tests/phpunit/unit-tests/forms/class-llms-test-form-handler.php:343]: you're right :D
