### PR TITLE
Fix display of merge codes in reusable blocks on certificates.

### LINKED ISSUE #2058: Merge codes on certificates don't work when part of a reusable block
### Reproduction Steps

1. Install LifterLMS
2. Make a certificate
3. Add a merge code
4. Add your merge code to a reusable block
5. View your certificate and it should display the merge code instead of what data the merge code should grab

video reproduction:
https://www.loom.com/share/ebf99da1642e4bf0b082e2b4b875f651

### Expected Behavior

The content the merge code should show would show up

### Actual Behavior

The acutal brackets show up {current_date}

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```

Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.9.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Blog (#2029) [[removed]/blog/]
Page On Front: Home (#1015) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0-rc.1
Course Catalog: Courses (#2202) [[removed]/courses/]
Membership Catalog: Membership Catalog (#2129) [[removed]/memberships/]
Student Dashboard: Dashboard (#2131) [[removed]/dashboard/]
Checkout Page: Purchase (#2130) [[removed]/purchase/]
Course Catalog Per Page: 30
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.16
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36


Theme
-------------------------------------------

Name: Kadence
Version: 1.1.14
Themeuri: https://www.kadencewp.com/kadence-theme/
Authoruri: https://www.kadencewp.com/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.0.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

course/lesson-preview.php (ver: 5.7.0): /srv/users/manager/apps/lifterlms-6-docs-will/public/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)
course/syllabus.php (ver: 4.4.0): /srv/users/manager/apps/lifterlms-6-docs-will/public/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ X] On a staging site
+ [ X] On a production website
+ [ X] With only LifterLMS and a default theme

### PR DESCRIPTION
**Pull request by pondermatic**
## Description
Fixed an issue where merge codes in reusable blocks on certificate templates were not replaced when displayed.

Reversed the order of merging the content and parsing the blocks.

Fixes #2058

## How has this been tested?
Manually and with a new unit test.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
I'm a little bit tired so I might miss something but:
1) this doesn't work on awarded certificates?
2) I might remember it wrong but I think we said we wanted to have merge codes to be dynamic in templates, and dynamic in awards until the awards are published. I don't see this logic implemented.

**Comment by pondermatic** [comment]
@eri-trabiccolo, you are correct. Awarded certificates are not yet working correctly. Right after I submitted this PR, I realized I didn't test awards and found this out. I changed the status immediately from "waiting review" to "in progress", but you may have started already. Sorry.

Sometimes I can see how to change a PR to draft mode, but not always and not on this one. :(

**Comment by eri-trabiccolo** [comment]
Ohh, alright.
About the draft mode, can't you see the link under Reviewers?
**Still in progress? Convert to draft.**

**Comment by pondermatic** [comment]
Ack! If it was a snake it would have bit me in the face! Thank you.

**Comment by pondermatic** [comment]
@gocodebox/engineering , ready for review.

File: includes/abstracts/llms-abstract-user-engagement.php [hunk 1]
```diff
@@ -232,10 +239,15 @@ public function sync( $context = 'update' ) {
...
+		$content = $template->get( 'content', true );
+		$blocks  = parse_blocks( $content );
+		$blocks  = LLMS_Forms::instance()->load_reusable_blocks( $blocks );
+		$content = serialize_blocks( $blocks );
+
 		// Copy the content, with optional merge codes and short codes, and optional block editor layout meta properties
 		// from the template to this awarded engagement.
-		$this->set( 'content', $template->get( 'content', true ) );
-		$this->set( 'content', $this->merge_content() );
+		$this->set( 'content', $this->merge_content( $content ) );
```
Comment (eri-trabiccolo) [inline includes/abstracts/llms-abstract-user-engagement.php]: can we wrap this into a method?
And then call this method from `LLMS_Controller_Awards::on_save()` too?
I wonder if the whole:
```
		$blocks  = parse_blocks( $content );
		$blocks  = LLMS_Forms::instance()->load_reusable_blocks( $blocks );
		$content = serialize_blocks( $blocks );
```
cannot just be included in `merge_content()` and executed if a new parameter "$load_reusable_blocks" is set to true.
So that we would have here:
`$this->set( 'content', $this->merge_content( $template->get( 'content', true ), true ) );`

with `function merge_content( $content = null, $load_reusable_blocks = false ){...}`.

File: includes/abstracts/llms-abstract-user-engagement.php [hunk 2]
```diff
@@ -200,18 +200,25 @@ public function is_awarded() {
...
 	 */
-	public function merge_content() {
+	public function merge_content( $content = null ) {
 
-		return $this->get( 'content', true );
+		if ( is_null( $content ) ) {
+			$content = $this->get( 'content', true );
+		}
+
+		return $content;
```
Comment (eri-trabiccolo) [inline includes/abstracts/llms-abstract-user-engagement.php]:
```suggestion
		return is_null( $content ) ? $this->get( 'content', true ) : $content;
```

File: includes/forms/class-llms-forms.php [hunk 3]
```diff
@@ -1024,45 +1024,47 @@ public function is_location_valid( $location ) {
...
-	 * By default, a reusable block contains a reference to the block post (which will be
-	 * loaded during rendering). This is problematic for us since we want to review then
-	 * entire block list so we can see all fields for validation purposes and so on.
+	 * A reusable block contains a reference to the block post, e.g. `<!-- wp:block {"ref":2198} /-->`,
+	 * which will be loaded during rendering.
 	 *
-	 * This function will replace each reusable block with the parsed blocks
-	 * from it's reference post.
+	 * Dereferencing the reusable blocks allows the entire block list to be reviewed and to validate all form fields.
+	 * This function will replace each reusable block with the parsed blocks from it's reference post.
```
Comment (eri-trabiccolo) [inline includes/forms/class-llms-forms.php]:
```suggestion
	 * This function will replace each reusable block with the parsed blocks from its reference post.
```

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
Couple of non crucial changes requested.
Looks solid to me, works good! <3

File: includes/abstracts/llms-abstract-user-engagement.php (hunk 1 above)
Comment (pondermatic) [reply includes/abstracts/llms-abstract-user-engagement.php]: That's a good idea. I thought about making a stand-alone function with those 3 lines to avoid duplicate code and considered adding them to `merge_content()`, but at the time I was too lazy to deal with classes extended from `LLMS_Abstract_User_Engagement`. I see a way to do that easily now.

**Review by eri-trabiccolo — APPROVED** [review]
Looks good to me <3

File: includes/abstracts/llms-abstract-user-engagement.php [hunk 4]
```diff
@@ -200,18 +200,32 @@ public function is_awarded() {
...
+	public function merge_content( $content = null, $load_reusable_blocks = false ) {
 
-		return $this->get( 'content', true );
+		if ( is_null( $content ) ) {
+			$content = $this->get( 'content', true );
+		}
+
+		if ( $load_reusable_blocks ) {
+			$blocks  = parse_blocks( $content );
+			$blocks  = LLMS_Forms::instance()->load_reusable_blocks( $blocks );
```
Comment (thomasplevy) [inline includes/abstracts/llms-abstract-user-engagement.php:217]: This line is the only coding problem I see in the entire PR... It works but now that we're using this outside of forms I'm feeling like the content of the `load_reuseable_blocks()` method could (should?) be moved to it's own utility function and then we can call that function here (and the forms class can call it as well). We should probably then deprecate the forms method. This does "inflate" the size of this PR... It's probably better that we just open up an enhancement issue to track this and do it at some point in the future.

**Review by thomasplevy — CHANGES_REQUESTED** [review]
This looks really good. Programmatically it all works exactly as we've discussed. Good job @pondermatic 

I did find what could be kind of a problem though... 

1) Edit an existing awarded cert
2) Add an existing (or create a new) reusable block to the cert content
3) Click the update button

Now in the DB the content of the certificate has been "merged" and the reusable block is gone but on the block editor's block list the reusable block is still present (and if there are any merge/shortocdes in the resuable block they will not have been merged like other content on the cert).

Luckily we already have some handling in place to address this as the same problem occurred with merge codes in the cert content.

This JS function just needs to be adjusted to, I think, also check for the presence of reusable blocks (in addition to the existing merge codes) and I think we'll be good to go:

https://github.com/gocodebox/lifterlms/blob/99a443c5da84913e65358cfba7957e1f083d4402/src/js/admin-certificate-editor/editor.js#L92-L130

File: includes/abstracts/llms-abstract-user-engagement.php (hunk 4 above)
Comment (pondermatic) [reply includes/abstracts/llms-abstract-user-engagement.php:217]: > I did find what could be kind of a problem though...

Thank you for catching this! I've committed a fix for this, but have not written a JavaScript test.

I've never been able to get the JavaScript testing framework working in my dev environment. It's been one npm package problem after another. Maybe this is the time to work through all the issues. Ugh.

> It works but now that we're using this outside of forms I'm feeling like the content of the load_reuseable_blocks() method could (should?) be moved to it's own utility function and then we can call that function here (and the forms class can call it as well). We should probably then deprecate the forms method.

I agree completely. I'll create a new issue for that.

**Comment by thomasplevy** [comment]
Nice work @pondermatic !
