### PR TITLE
Bug fix #1239

### LINKED ISSUE #1239: Limit Attempt Switch-Number is a text field
### Reproduction Steps

+ Open a quiz lesson in the builder 
+ Look at the CSS structure for Limit Attempts

### Expected Behavior

+ I guess it should be a number field?

### Actual Behavior

+ it's a text field that accepts numbers just fine.

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [X] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [X] With only LifterLMS and a default theme

HS-128036  Customer attached a screenshot.

### LINKED ISSUE #1379: Certificates: New sharing button creates confusing user experience when button is next to the "Save" button
### Reproduction Steps

+ View an earned certificate as a student
+ Click "Enable Sharing" to allow a certificate to be shared

### Expected Behavior

+ Users are expecting that a link will be provided to them which they can use to share the certificate
+ Some users expect that they must also "Save" the certificate (using the "Save" button) after enabling/disabling sharing

### Actual Behavior

+ Clicking "save" is not necessary (as this is actually an export button)
+ There is no user feedback indicating what URL should be used to "Share" the certificate after sharing is enabled.

### Proposal

+ The language of the "Save" button should be changed to "Download" or "Export"
+ When sharing is enabled, a readonly text input should be output with the certificate's URL populated in it. This will help users identify what URL should be used to share the certificate.

### PR DESCRIPTION
**Pull request by imknight**
## Description
added switch case on SetttingsFields.js to handle switch-number field type using the number type as a default input type.

Fixes #1239

## How has this been tested?
adding a new quiz, turn on limit attempt, the field has become number field.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [X] My code has been tested.
- [  ] My code passes all existing automated tests. Having an issue to setup this
- [X] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: assets/js/builder/Views/SettingsFields.js [hunk 1]
```diff
@@ -341,6 +341,10 @@ define( [], function() {
 					defaults.input_type = 'number';
 				break;
 
+				case 'switch-number':
+					defaults.input_type = 'number';
+				break;
+
```
Comment (thomasplevy) [inline assets/js/builder/Views/SettingsFields.js]: Rather than creating a new case that's identical to the `number` case on line 340 we can add `switch-number` to this case.

This would work identically to the `editor` and `switch-editor` cases on 328 & 329

**Review by thomasplevy — CHANGES_REQUESTED** [review]
See comments below

File: assets/js/builder/Views/SettingsFields.js (hunk 1 above)
Comment (imknight) [reply assets/js/builder/Views/SettingsFields.js]: got it.
