### PR TITLE
Fix Issue/1029

### LINKED ISSUE #1029: Adding an existing lesson to a course "removes" the lesson's author
### Reproduction Steps

+ create a lesson and verify it has an author assigned
+ create a course
+ open the course builder, create a section and add the previously created lesson to this course
+ save
+ check the lesson's author

### Expected Behavior

+ I would expect to still see the same lesson author as before adding the lesson to the course

### Actual Behavior

+ no lesson author anymore

### Error Messages / Logs

```
[25-Feb-2020 20:57:05 UTC] PHP Warning:  strip_tags() expects parameter 1 to be string, array given in /srv/www/wordpress-one/public_html/wp-content/plugins/lifterlms/includes/abstracts/abstract.llms.post.model.php on line 901
```

### System Information

LifterLMS 3.37.10

### Related User Information
HS-110280

Basically, from a rapid view/dump, the lesson's author is an absint but we try to set an array of the type
```
[
    'description' => 
    'email' => 
    'first_name' => 
    'id' => 1
    'last_name' => 
]
```

### PR DESCRIPTION
**Pull request by thomasplevy**
## Description

Fixes #1029
Additionally addresses a PHP notice encountered during the same reproduction steps in issue 1029

## How has this been tested?

Tested manually for UI/UX in browser on the builder.
Passes existing phpunit tests.

## Types of changes
Bug fix, non breaking

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: assets/js/builder/Models/Course.js [hunk 1]
```diff
@@ -1,8 +1,10 @@
 /**
  * Course Model
  *
- * @since    3.16.0
- * @version  3.24.0
+ * @since 3.16.0
+ * @since 3.24.0 Added 	get_total_points()` method.
```
Comment (eri-trabiccolo) [inline assets/js/builder/Models/Course.js]:
```suggestion
 * @since 3.24.0 Added `get_total_points()` method.
```

File: assets/js/builder/Models/Course.js [hunk 2]
```diff
@@ -90,17 +95,22 @@ define( [ 'Collections/Sections', 'Models/_Relationships', 'Models/_Utilities' ]
...
 		 * Add a new lesson to the course
 		 *
-		 * @param    obj   data   lesson data
-		 * @return   obj          Backbone.Model of the lesson
-		 * @since    3.16.0
-		 * @version  3.16.0
+		 * @since 3.16.0
+		 *
+		 * @param  {Object} data Lesson data.
+		 * @return {Object}      Backbone.Model of the lesson.
```
Comment (eri-trabiccolo) [inline assets/js/builder/Models/Course.js]:
```suggestion
		 * @param {Object} data Lesson data.
		 * @return {Object} Backbone.Model of the lesson.
```

File: assets/js/builder/Models/Course.js [hunk 3]
```diff
@@ -134,10 +144,10 @@ define( [ 'Collections/Sections', 'Models/_Relationships', 'Models/_Utilities' ]
...
 		 * Add a new section to the course
 		 *
-		 * @param    obj   data   section data
-		 * @return   void
-		 * @since    3.16.0
-		 * @version  3.16.0
+		 * @since 3.16.0
+		 *
+		 * @param  {Object} data Section data.
+		 * @return {Void}
```
Comment (eri-trabiccolo) [inline assets/js/builder/Models/Course.js]:
```suggestion
		 * @param {Object} data Section data.
		 * @return {Void}
```
