### PR TITLE
Fix spanish states

### LINKED ISSUE #2243: Spain missing Provinces
### Reproduction Steps

+ HS-200045
+ User reported that several provinces and regions were either missing or wrong. Provided this as a list: https://public.opendatasoft.com/explore/dataset/provincias-espanolas/table/?sort=provincia

I'm not sure if there is a way to verify this is correct but we could maybe use it as a reference point?

### Expected Behavior

+ There should be more/separate provinces and regions

### Actual Behavior

+ Missing places

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description

Fixes #2243

## How has this been tested?
manually
and new unit tests

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: includes/functions/updates/llms-functions-updates-6100.php [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+		'CM' => '',
+		'CT' => '',
+		'EX' => '',
+		'GA' => '',
+		'RI' => '',
+		'MD' => '',
+		'MC' => '',
+		'NC' => '',
+		'SA' => '',
+		'VC' => '',
```
Comment (thomasplevy) [inline includes/functions/updates/llms-functions-updates-6100.php]:
```suggestion
```

VC is mapped above to V

File: includes/functions/updates/llms-functions-updates-6100.php [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+		'CN' => '',
+		'CL' => '',
+		'CM' => '',
+		'CT' => '',
+		'EX' => '',
+		'GA' => '',
+		'RI' => '',
+		'MD' => '',
+		'MC' => '',
+		'NC' => '',
```
Comment (thomasplevy) [inline includes/functions/updates/llms-functions-updates-6100.php]:
```suggestion
```

Mapped above

File: includes/functions/updates/llms-functions-updates-6100.php [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+		'PV' => '',
+		'CN' => '',
+		'CL' => '',
+		'CM' => '',
+		'CT' => '',
+		'EX' => '',
+		'GA' => '',
+		'RI' => '',
+		'MD' => '',
+		'MC' => '',
```
Comment (thomasplevy) [inline includes/functions/updates/llms-functions-updates-6100.php]:
```suggestion
```

Mapped above

File: includes/functions/updates/llms-functions-updates-6100.php [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+		'AR' => '',
+		'PV' => '',
+		'CN' => '',
+		'CL' => '',
+		'CM' => '',
+		'CT' => '',
+		'EX' => '',
+		'GA' => '',
+		'RI' => '',
+		'MD' => '',
```
Comment (thomasplevy) [inline includes/functions/updates/llms-functions-updates-6100.php]:
```suggestion
```

Mapped above

File: includes/functions/updates/llms-functions-updates-6100.php [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+		'AN' => '',
+		'AR' => '',
+		'PV' => '',
+		'CN' => '',
+		'CL' => '',
+		'CM' => '',
+		'CT' => '',
+		'EX' => '',
+		'GA' => '',
+		'RI' => '',
```
Comment (thomasplevy) [inline includes/functions/updates/llms-functions-updates-6100.php]:
```suggestion
```

Mapped above

File: .changelogs/issue_2243.yml [hunk 6]
```diff
@@ -0,0 +1,5 @@
+significance: patch
+type: fixed
+links:
+  - "#2243"
+entry: "Updated Spain's provinces: added missing and fixed wrong ones."
```
Comment (thomasplevy) [inline .changelogs/issue_2243.yml]:
```suggestion
entry: "Updated Spain's provinces list."
```

**Review by thomasplevy — CHANGES_REQUESTED** [review]

**Review by thomasplevy — APPROVED** [review]
