### PR TITLE
Fix fatal when downloading a certificate if mime_content_type PHP fun…

### LINKED ISSUE #1120: Fatal when downloading a certificate if mime_content_type PHP function not available.
### Reproduction Steps

+ On a server where the PHP function `mime_content_type()` is not available download/save a certificate

### Expected Behavior

+ I expect to download the certificate without any issues

### Actual Behavior

+ Cannot download the certificate due to a fatal error

### Error Messages / Logs

It should be a classic PHP fatal for non existent functions.

### System Information

same as #1118 

### Browser, Device, and Operating System Information

n/a

### Related User Information

https://wordpress.org/support/topic/certificate-download-error/

We should take into account the non availability of this function (e.g. jetpack and several others do it), a simple but nice solution would be something of the sort:
https://github.com/inpsyde/backwpup/blob/master/vendor/inpsyde/backwpup-shared/src/File/MimeTypeExtractor.php

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
…ction not available

## Description
Fixes #1120

## How has this been tested?

I've tested it only manually, with certificates containing jpg and png images.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests.
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by thomasplevy** [comment]
I'd like to see some tests added to test the method in the new class

**Comment by eri-trabiccolo** [comment]
Yeah I think I don't know how to really test all the else cases :)

**Comment by thomasplevy** [comment]
@eri-trabiccolo In general without redefining pluggable wrappers around every php core function it's going to be impossible to get test coverage on the fallback functions that may or may not be defined... However, we can quite easily cover the "main" condition

https://github.com/gocodebox/lifterlms/blob/c89819dd56ce2a71fd2addaa410412f6b486d6b2/includes/class-llms-mime-type-extractor.php#L223-L225

and the final return:

https://github.com/gocodebox/lifterlms/blob/c89819dd56ce2a71fd2addaa410412f6b486d6b2/includes/class-llms-mime-type-extractor.php#L237

I think two tests would do it fine:

Test A: Tests a few mime types we can expect to work, like png/jpg and another one, maybe a txt type or something.

Test B: Tests an unknown mime-type not found in the list (make up a fake one)

This will then generally cover the conditions and won't give us 100% test coverage of the new code but it actually gives us close 100% realistic coverage of what we can cover with phpunit

**Comment by thomasplevy** [comment]
Since this also relies on passing in an actual readable file, you'll want to take on the strategy employed  by our assignments add-on to test file uploads -- basically adding a new mock asset (an actual image) into the /tests/assets directory which will actually be readable and then they can be physically testsed against the file

We already have a few mock assets in the core but don't have any images, add a new one (grab something off unsplash like we did for assignments: https://github.com/gocodebox/lifterlms-assignments/tree/master/tests/assets

File: tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+	 *
+	 * @var array
+	 */
+	protected $files = array(
+		'json' => 'import-error.json',
+		'jpg'  => 'christian-fregnan-unsplash.jpg',
+	);
+
+	/**
+	 *
```
Comment (thomasplevy) [inline tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php:25]:
```suggestion
	 * Test from_file_path() for a file with a mime-type that exists
	 *
```

File: tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+		global $lifterlms_tests;
+		$this->assertEquals(
+			'image/jpeg',
+			LLMS_Mime_Type_Extractor::from_file_path( $lifterlms_tests->assets_dir . $this->files['jpg'] )
+		);
+
+	}
+
+	/**
+	 *
```
Comment (thomasplevy) [inline tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php:41]:
```suggestion
	 * Test from_file_path() for a mime-type not found in our list
	 *
```

File: tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+				LLMS_Mime_Type_Extractor::DEFAULT_MIME_TYPE,
+				LLMS_Mime_Type_Extractor::from_file_path( $lifterlms_tests->assets_dir . $this->files['json'] )
+			);
+		}
+
+
+	}
+
+	/**
+	 *
```
Comment (thomasplevy) [inline tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php:72]:
```suggestion
	 * Test from_file_path() for a file that does not exist
	 *
```

File: tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+	 * @since [version]
+	 *
+	 * @return void
+	 */
+	public function test_mime_type_not_exitent() {
```
Comment (thomasplevy) [inline tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php:77]: Typo

```suggestion
	public function test_mime_type_not_existent() {
```

File: tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+		global $lifterlms_tests;
+		$this->assertEquals(
+			LLMS_Mime_Type_Extractor::DEFAULT_MIME_TYPE,
+			LLMS_Mime_Type_Extractor::from_file_path( $lifterlms_tests->assets_dir . 'SomeoneJoinsSomethingTheyDoNotBelongTo.jpg' )
+		);
+
+	}
+
+	/**
+	 *
```
Comment (thomasplevy) [inline tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php:88]:
```suggestion
	 * Test from_file_path() when checking a directory
	 *
```

File: tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php [hunk 6]
```diff
@@ -0,0 +1,106 @@
...
+	 * @since [version]
+	 *
+	 * @return void
+	 */
+	public function test_mime_type_not_in_list() {
+
+		global $lifterlms_tests;
+
+		// I expect json to be recognized either by one of the fallback functions as 'text/plain'.
+		if ( function_exists( 'finfo_file' ) ) {
```
Comment (thomasplevy) [inline tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php:53]: travis tests are failing on php 7.4 where `finfo_file()` exists.

I've been able to reproduce locally on my end too. It looks like `finfo_file()` on 7.4 at least responds with `application/json` for the tested file but it returns as `text/html` when using the `sample-course.json` file found in the core plugin `sample-data` directory.

A bit of research shows that the function uses the file's "signature" to determine the filetype and JSON files can have varied signatures based on their content. I guess the sample course has some HTML in it causing it to look like an HTML from a "signature" perspective.

I don't fully understand it all but I'm leaning towards simply scrapping this test since it's going to respond differently per PHP version and since for our purposes we won't be using it to identify JSON files and we can simply move on.

Comment (eri-trabiccolo) [reply tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php:53]: This is annoying I just wanted to cover the 'not in list'. :/

Comment (thomasplevy) [reply tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php:53]: Ahh i see... I'm not sure if there's going to be a way to do that given the way finfo_file works

Maybe creating a text file in the tests/assets directory with no content that has a fake file extension, eg: `fake-mime.fakemime`

The signature on that might still read as a text file (or maybe not) but it should fallback correctly anyway then, right?

Comment (thomasplevy) [reply tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php:53]: Also, sorry.

Comment (eri-trabiccolo) [reply tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php:53]: I actually tested that locally and when empty (created with `touch`) it was recognized as empty inode, if with text inside, it was recognized as text...

Comment (thomasplevy) [reply tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php]: @eri-trabiccolo cool you fixed it!

Comment (eri-trabiccolo) [reply tests/phpunit/unit-tests/class-llms-test-mime-type-extractor.php]: well you know, I cheated, I mean we weren't interested in a deep test :D
