### PR TITLE
Don't process non-existent courses during course data processing

### LINKED ISSUE #1598: Course data processor generates PHP fatal error if the course does not exist.
### Reproduction Steps

I don't know how to reliably reproduce the root cause of this issue, which is a course data task being scheduled that references a deleted course.

But when it does happen, `LLMS_Processor_Course_Data->task()` tries to get a course that no longer exists, which generates `PHP Fatal error:  Uncaught Error: Call to a member function set() on null` messages in the PHP error log.

### Expected Behavior

The task should be deleted.

### Actual Behavior

`PHP Fatal error:  Uncaught Error: Call to a member function set() on null` messages in the PHP error log.

LifterLMS background processor tasks accumulate.

### Error Messages / Logs

```
[16-Apr-2021 14:15:27 UTC] PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /var/www/vistacast.com/lms-gpi/wordpress/wp-content/plugins/lifterlms/includes/processors/class.llms.processor.course.data.php:394
Stack trace:
#0 /var/www/vistacast.com/lms-gpi/wordpress/wp-content/plugins/lifterlms/includes/libraries/wp-background-processing/wp-background-process.php(270): LLMS_Processor_Course_Data->task(Array)
#1 /var/www/vistacast.com/lms-gpi/wordpress/wp-content/plugins/lifterlms/includes/libraries/wp-background-processing/wp-background-process.php(393): WP_Background_Process->handle()
#2 /var/www/vistacast.com/lms-gpi/wordpress/wp-includes/class-wp-hook.php(292): WP_Background_Process->handle_cron_healthcheck()
#3 /var/www/vistacast.com/lms-gpi/wordpress/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#4 /var/www/vistacast.com/lms-gpi/wordpress/wp-includes/plugin.php(551): WP_Hook->do_action(Array)
#5 /var/www/vistacast.com/lms-gpi/wordpress/wp-cron.php(138): do_action_ref_array('llms_background...', Array)
#6 {main}
  thrown in /var/www/vistacast.com/lms-gpi/wordpress/wp-content/plugins/lifterlms/includes/processors/class.llms.processor.course.data.php on line 394
```

### Possible Solution

```php
	public function task( $args ) {

		$this->log( sprintf( 'Course data calculation task called for course %1$d with args: %2$s', $args['post_id'], wp_json_encode( $args ) ) );

		$course = llms_get_post( $args['post_id'] );

		# Do not perform the task if course does not exist.
		if ( ! $course ) {
			return false;
		}

		// Lock the course against duplicate processing.
		$course->set( 'temp_calc_data_lock', 'yes' );


```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://lms-gpi.vistacast.com
Site Url: https://lms-gpi.vistacast.com
Login Url: https://lms-gpi.vistacast.com/wp-login.php
Version: 5.7.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Dashboard (#8) [https://lms-gpi.vistacast.com/]
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show On Front: page
Wp Cron: No


Settings
-------------------------------------------

Version: 4.18.0
Db Version: 4.18.0
Course Catalog: Course Catalog (#5) [https://lms-gpi.vistacast.com/courses/]
Membership Catalog: Membership Catalog (#6) [https://lms-gpi.vistacast.com/memberships/]
Student Dashboard: Dashboard (#8) [https://lms-gpi.vistacast.com/]
Checkout Page: Purchase (#7) [https://lms-gpi.vistacast.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: info@gainingpowernow.com
Email From Name: Gaining Power Institute, LLC
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 3000
Php Max Upload Size: 202 MB
Php Memory Limit: 328M
Php Post Max Size: 208M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.2.34
Software: Apache/2.4.6
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 3.2.0
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

Admin Columns Pro: 5.4.4
Admin Columns Pro - Meta Box: 1.1
Advanced Post Types Order: 4.3.8.6
Astra Pro: 3.1.0
CoolSys: 1.4.0
Experience Visualizer: 2.7.0
Fast User Switching: 1.4.9
Force Login: 5.5
H5P: 1.15.0
H5P xAPI: 0.1.6
LifterLMS: 4.18.0
LifterLMS Configurator: 2.0.3
LifterLMS xAPI: 1.3.0.1.1
OpenID Connect Generic: 3.8.2
Responsive Lightbox: 1.3.4
User Role Editor: 4.59
Wordfence Security: 7.5.2
WordPress Persistent Login (Premium): 1.3.21
WP Crontrol: 1.10.0
WP Rollback: 1.7.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

```

</details>

This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### PR DESCRIPTION
**Pull request by thomasplevy**
## Description

Fixes #1598 

## How has this been tested?

+ New + existing phpunit tests

## Types of changes
+ Bugfix

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by pondermatic** [comment]
This fix looks great!

File: tests/phpunit/unit-tests/processors/class-llms-test-processor-course-data.php [hunk 1]
```diff
@@ -405,4 +404,48 @@ public function test_task() {
...
+
+		$tests = array(
+			// Deleted course.
+			$this->factory->post->create( array( 'post_type' => 'course' ) ),
+
+			// Not a course.
+			$this->factory->post->create(),
+		);
+
+		wp_delete_post( $tests[0], true );
```
Comment (eri-trabiccolo) [inline tests/phpunit/unit-tests/processors/class-llms-test-processor-course-data.php:424]:
```suggestion
```
we already delete this post at line 431, right?

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
fine for me, except for the minor changes requested in the tests.

File: tests/phpunit/unit-tests/processors/class-llms-test-processor-course-data.php (hunk 1 above)
Comment (thomasplevy) [reply tests/phpunit/unit-tests/processors/class-llms-test-processor-course-data.php:424]: actually the issue is the deletion on 431, I only want to be testing that a deleted course and the other's should exist before running the test otherwise I'm testing the same thing (essentially) twice.

Either way, thanks for noticing
