### PR TITLE
content filtering conditions

### LINKED ISSUE #1530: Cannot properly create quizzes when the Yoast SEO plugin is active
### Reproduction Steps

+ Install and activate the Yoast SEO plugin
+ Open the course builder, add a quiz to a lesson
+ Save the changes (or wait for the auto-save if you're not a control-freak :P)

### Expected Behavior

+ I'd expect the changes (quiz addition) to be saved with no errors

### Actual Behavior

+ The quiz is created but only "partially" saved - meaning that not all of its properties have been saved. Plus an error is shown in the builder:
Schermata 2021-02-15 alle 16 49 22

It seems that when saving (I think on post insertion?!) Yoast SEO "expands" the post content (meaning that applies `'the_content'` filter), in this case the quiz content, when the quiz's lesson meta has not been set yet.
But in our template we just assume that this is always set.

### Error Messages / Logs

```
[15-Feb-2021 15:48:48 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on bool in /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/templates/quiz/start-button.php:26

```

### System and Environment Information
(customer's system report)
<details>
<summary>System Report</summary>

```
System Report:
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php?itsec-hb-token=wplogit
Version: 5.6.1
Debug Mode: No
Debug Log: Yes
Debug Display: No
Locale: en_US
Multisite: No
Page For Posts: Blog (#181) [[removed]/blog/]
Page On Front: Home (#130) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.15.0
Db Version: 4.15.0
Course Catalog: Course Catalog (#7) [[removed]/courses/]
Membership Catalog: Membership Catalog (#8) [[removed]/memberships/]
Student Dashboard: Members Dashboard (#60) [[removed]/members-dashboard/]
Checkout Page: Purchase (#9) [[removed]/purchase/]
Course Catalog Per Page: -1
Course Catalog Sorting: title,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint:
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: medium
Terms Required: yes
Terms Page: Disclaimer and Terms of Use (#391) [[removed]/disclaimer-and-terms-of-use/]
Checkout Names: required
Checkout Address: hidden
Checkout Phone: required
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: hidden
Registration Phone: required
Registration Voucher: optional
Registration Email Confirmation: yes
Account Names: required
Account Address: hidden
Account Phone: required
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image: 600
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Authorize.Net: Disabled
Authorize.Net Test Mode: Disabled
Authorize.Net Logging:
Authorize.Net Order: 1
PayPal: Enabled
PayPal Test Mode: Disabled
PayPal Logging: yes
PayPal Order: 1
Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: yes
Stripe Order: 1
Manual: Disabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 128 MB
Php Memory Limit: 512M
Php Post Max Size: 256M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 300
Php Version: 7.4.11
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36


Theme
-------------------------------------------

Name: WPCrafter LMS
Version: 0.1
Themeuri: https://wpcrafter.com
Authoruri: https://wpcrafter.com
Template: generatepress
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

AnyImage.io Integration: 2.0.0
Classic Editor: 1.6
Cookie Notice & Compliance for GDPR / CCPA: 2.0.2
Duplicate Page: 4.3
Dynamic Visibility for Elementor: 3.0.1
Elementor: 3.1.1
Elementor Addons & Templates - Sizzify Lite: 1.3.2
Elementor Pro: 3.0.10
Google Analytics Dashboard for WP (GADWP): 6.6.0
Google Analytics for WordPress by MonsterInsights: 7.16.0
GP Premium: 1.12.3
Health Check & Troubleshooting: 1.4.5
Imagify: 1.9.14
Insert Google Analytics Id: 1.1.3
iThemes Security Pro: 6.8.3
LifterLMS: 4.15.0
LifterLMS Advanced Quizzes: 1.1.1
LifterLMS Advanced Videos: 1.0.0-beta.13
LifterLMS Assignments: 1.1.11
LifterLMS Authorize.Net Payment Gateway: 1.1.0
LifterLMS ConvertKit: 2.1.0
LifterLMS Custom Fields: 1.0.2
LifterLMS Customizations: 1.0.0
LifterLMS Helper: 3.1.0
LifterLMS MailChimp Add-on: 3.1.2
LifterLMS PayPal Gateway: 1.3.0
LifterLMS Social Learning: 1.3.0
LifterLMS Stripe Payment Gateway: 5.3.1
LifterLMS WPForms: 1.1.1
Mail On Update: 5.4.13
My Custom Functions: 4.48
Nav Menu Roles: 2.0.0
OptinMonster: 2.1.1
Page Templater For Elementor: 1.2.9
PHP Compatibility Checker: 1.5.0
UpdraftPlus - Backup/Restore: 2.16.47.25
Uptime Robot Widget: 1.8.2
User Switching: 1.5.6
WP Content Copy Protection (Lite): 2.0.3
WP Crontrol: 1.9.1
WP File Manager: 7.0
WPForms: 1.6.4.1
WP Mail SMTP: 2.6.0
WP Rocket: 2.10.7
Yoast SEO: 15.8


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS ConvertKit: No
LifterLMS WPForms: Yes
LifterLMS MailChimp: No
LifterLMS Social Learning: No
Videos: Vimeo: Yes
Videos: Wistia: No
Videos: YouTube: No


Template Overrides
-------------------------------------------

```

</details>

### This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

### Related User Information
HS-154941

### LINKED ISSUE #1536: Cannot import/clone courses with quizzes when the Yoast SEO plugin is active
### Reproduction Steps

+ Make sure the Yoast SEO plugin is active
+ Import a course with a quiz, e.g. the LifterLMS Quickstart Course

### Expected Behavior

+ Import should go through

### Actual Behavior

+ Import hangs and error is logged

This is something expected actually, as it's similar to the #1530 issue.
I thought about it tonight and verified it now.

### Error Messages / Logs

```
[19-Feb-2021 08:49:22 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on bool in /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/templates/quiz/start-button.php:26
Stack trace:
#0 /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/includes/functions/llms.functions.template.php(120): include()
#1 /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/includes/functions/llms.functions.templates.quizzes.php(217): llms_get_template('quiz/start-butt...')
#2 /shared/httpd/mywp/wordpress.git/wp-includes/class-wp-hook.php(292): lifterlms_template_start_button('')
#3 /shared/httpd/mywp/wordpress.git/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#4 /shared/httpd/mywp/wordpress.git/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#5 /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/templates/content-single-quiz-after.php(11): do_action('lifterlms_singl...')
#6 /shared/httpd/mywp/wordpress.git/wp-includes/template.php(732): require('/shared/httpd/m...')
#7 /shared/htt in /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/templates/quiz/start-button.php on line 26

```

I think we need to fix this in the template as well, because I guess we can have this issue when retrieving an orphan quiz's content (rendered sub-prop) via rest-api too.

### System and Environment Information

<summary>System Report</summary>

```
LifterLMS 4.16.0
Yoast SEO 15.8
```

### This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### PR DESCRIPTION
**Pull request by thomasplevy**
## Description

I think this is a descent approach to fixing the issue(s) we've been encountering as a result of recent changes introduced into Yoast 15.8.

The changes which have caused these errors to start appearing were introduced in 15.8, specifically https://github.com/Yoast/wordpress-seo/commit/9b4f7caa591ea570ccd7dcec56968b21954ecdd0 which loads the `$post` global.

Previously, since the global wasn't setup in the conditions where we're now encountering issues (the course builder and during cloning / importing on the admin panel) we didn't have any problems. But now that the `$post` global exists on sites running Yoast (it looks like this is loaded on the admin panel by Yoast intentionally but I can't tell exactly why, nor have I tried to figure it out).

This PR introduces conditional loading of our filters so that on the admin panel (generally, even though we care specifically about the course builder and course importer / cloninig function) and during REST requests the templates and restriction logic handled by `llms_get_post_content()` isn't executed.

This is a WIP. I haven't finished testing it and probably even writing it. I'm hoping to get this deployed this weekend because Yoast conflict bug reports are coming in regularly since 15.8 dropped and the severity is raising for us as a result.

Fixes #1536 
Fixes #1530 

This should also fix https://github.com/gocodebox/lifterlms-assignments/issues/55 (but I haven't run a test against this yet, just theoretically)

## How has this been tested?

+ Added new unit tests, needs more thorough testing to actually ensure the conflict with Yoast (and theoretical conflict with other plugins) doesn't happen anymore. I think this will all fix it based on @eri-trabiccolo recommendations across the various related issues and (failed) PRs to fix the issue.

## Types of changes

+ bug fix

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: includes/functions/llms-functions-content.php [hunk 1]
```diff
@@ -84,7 +83,7 @@ function llms_get_post_content( $content ) {
 		/**
 		 * Filter the post_content of a LifterLMS post type.
 		 *
-		 * @since Unknown.
+		 * @since [version]
```
Comment (thomasplevy) [inline includes/functions/llms-functions-content.php]:
```suggestion
		 * @since Unknown
```

File: includes/functions/llms-functions-content.php [hunk 2]
```diff
@@ -15,83 +15,129 @@
...
+	 */
+	if ( apply_filters( 'llms_should_filter_post_content', $should_filter ) ) {
+		return add_filter( 'the_content', 'llms_get_post_content' );
 	}
+
+	return false;
+
 }
-add_filter( 'the_content', 'llms_get_post_content' );
+add_action( 'init', 'llms_post_content_init' );
```
Comment (eri-trabiccolo) [inline includes/functions/llms-functions-content.php]: normally this file is already included at `init|10`:
https://github.com/gocodebox/lifterlms/blob/4.16.0/class-lifterlms.php#L119

Except when that function is called directly, e.g.:
https://github.com/gocodebox/lifterlms/blob/4.16.0/includes/class.llms.emails.php#L62
https://github.com/gocodebox/lifterlms/blob/4.16.0/includes/admin/class.llms.admin.import.php#L284

So maybe this line could be:
`current_filter( 'init' ) ? llms_post_content_init() : add_action( 'init', 'llms_post_content_init' );`

so that:
- the function is executed
- we're not forced to change the priority altering the original "execution flow".

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
While I see your reasons here I'm not sure this is the **best** approach.
At least it's not so for the REST api when returning the `llms_post` content "rendered", if it's not built with the block editor. In the content rendered, in fact, we display the post as it appears in front, so, to say, for a course, it'll display the instructors, the pricing table etc... which when using the block editor they're just blocks, but when not using it they are hooked to action hooks fired in templates loaded by `llms_get_post_content`. 
Also content restrictions which do not imply a redirect are handled there too.

If we decide this is the way to go, we need to add back this filter, e.g. here:
https://github.com/gocodebox/lifterlms-rest/blob/1.0.0-beta.18/includes/abstracts/class-llms-rest-posts-controller.php#L835

Right?

Because ideally, we should skip the content filtering only when inserting (updating) posts either in admin or REST requests: skip when inserting, but not when returning the inserted one.

Also, while this fixes all the issues you cited, in the assignment plugin we [use a similar filter](https://github.com/gocodebox/lifterlms-assignments/blob/1.1.11/includes/functions-llms-assignments-templates.php#L101), which anyways doesn't produce any issues because the template it loads are fine :D

File: includes/functions/llms-functions-content.php (hunk 2 above)
Comment (thomasplevy) [reply includes/functions/llms-functions-content.php]: @eri-trabiccolo in both of these manually called scenarios we don't actually care if the filter is loaded though, right?

1) During email loading we don't need to add any of our custom content to the qualifying post types
2) Uploading an import happens on the admin panel, where we wouldn't apply the filter anyway

In both scenarios it's probably preferable not to have the filter loaded from at the very least a minor performance perspective.

Do you agree?

Comment (eri-trabiccolo) [reply includes/functions/llms-functions-content.php]: @thomasplevy yeah I agree, I was exposing the current scenario.
So we can just go with
`llms_post_content_init()` instead of `add_action( 'init', 'llms_post_content_init' );`

File: includes/admin/class.llms.admin.builder.php [hunk 3]
```diff
@@ -318,6 +318,7 @@ private static function get_template( $template, $vars = array() ) {
 	 * @since 3.19.2 Unknown.
 	 * @since 4.16.0 Remove all filters/actions applied to the title/content when handling the ajax_save by deafault.
 	 *               This is specially to prevent plugin conflicts, see https://github.com/gocodebox/lifterlms/issues/1530.
+	 * @since [version] Remove `remove_all_*` hooks added in version 4.16.0.
```
Comment (eri-trabiccolo) [inline includes/admin/class.llms.admin.builder.php:321]: mmm so this file header's version tag must be updated.

File: includes/functions/llms-functions-content.php [hunk 4]
```diff
@@ -15,83 +15,131 @@
...
 	 *
 	 * @param string $content WP_Post post_content.
 	 * @return string
 	 */
 	function llms_get_post_content( $content ) {
 
 		global $post;
-		if ( ! $post instanceof WP_Post ) {
+		if ( ! $post instanceof WP_Post || ! in_array( $post->post_type, array( 'course', 'llms_membership', 'lesson', 'llms_quiz' ), true ) ) {
 			return $content;
```
Comment (eri-trabiccolo) [inline includes/functions/llms-functions-content.php:31]: I'm just realizing the prior to this PR we basically passed all the posts' contents through the filter `llms_get_post_content`, while now we do that only for those "special" post types... mmm.
Am I wrong?
I think it's better this way, but this is a change in behavior... right?

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
only a doc to be added.
And a consideration...

File: includes/functions/llms-functions-content.php (hunk 4 above)
Comment (thomasplevy) [reply includes/functions/llms-functions-content.php:31]: mmm yea, you're right...

It's both good and bad though...

I think the fact that we don't filter other content types is possibly a problem

The fact that we don't run them through `do_shortcode()` is beneficial

Comment (thomasplevy) [reply includes/functions/llms-functions-content.php:31]: Right?

Comment (thomasplevy) [reply includes/functions/llms-functions-content.php:31]: @eri-trabiccolo check my update please

Comment (eri-trabiccolo) [reply includes/functions/llms-functions-content.php:31]: Yeah...

Comment (eri-trabiccolo) [reply includes/functions/llms-functions-content.php:31]: @thomasplevy looks good, although I wonder why we have `do_shortcode` there.
Our filter is added at priority 10, while `do_shortcode` is added by wp core at priority 11.

Maybe it wasn't so back in the past?

Comment (thomasplevy) [reply includes/functions/llms-functions-content.php:31]: @eri-trabiccolo It's possible that it's never been needed. I'm not sure. I'm not digging into this right now.

Comment (eri-trabiccolo) [reply includes/functions/llms-functions-content.php:31]: I'm totally with you
