### PR TITLE
Fix cloned courses retaining original course id in open/close settings

### LINKED ISSUE #1212: Cloned courses retain original course id in open/close settings
### Reproduction Steps

+ Clone a course that has a course open date

### Expected Behavior

+ the cloned course does not have the course open date saved
+ the cloned course has it's own id number saved in the shortcode for open date

### Actual Behavior

+ it retains the information for course open and the previous course's id in the metabox

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: http://fresh.local
Site Url: http://fresh.local
Login Url: http://fresh.local/wp-login.php
Version: 5.4.2
Debug Mode: Yes
Debug Log: No
Debug Display: No
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#2457) [http://fresh.local/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 3.41.0
Db Version: 3.41.0
Course Catalog Per Page: -1
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: optional
Checkout Phone: hidden
Checkout Email Confirmation: no
Open Registration: no
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: GB
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Name: fresh
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: no
Stripe Order: 1
Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.25
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 8 MB
Php Memory Limit: 256M
Php Post Max Size: 8M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.1
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 2.4.5
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

LifterLMS: 3.41.0
LifterLMS Helper: 3.0.2



Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
WooCommerce: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [X] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [X] With only LifterLMS and a default theme

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description

Fixes #1212 

## How has this been tested?
manually and with unit tests

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: includes/class-llms-generator-courses.php [hunk 1]
```diff
@@ -691,4 +691,45 @@ protected function setup_raw_for_clone( $raw ) {
...
+
+			/**
+			 * Replace old post ID with new cloned post ID in course/enrollment
+			 * message shortcodes.
+			 */
+			foreach ( $replace_id_props as $key ) {
+				if ( isset( $raw[ $key ] ) ) {
+					$raw[ $key ] = str_replace( $find, $replace, $raw[ $key ] );
+				}
+			}
```
Comment (thomasplevy) [inline includes/class-llms-generator-courses.php]: (Some) shortcode attributes will work both with and without quotes (and it's possible they'll work with single quotes also). Possibly a `preg_replace()` regex would work to accommodate all potential iterations of the shortcode attributes.

**Review by thomasplevy — CHANGES_REQUESTED** [review]

File: includes/class-llms-generator-courses.php (hunk 1 above)
Comment (eri-trabiccolo) [reply includes/class-llms-generator-courses.php]: solved in [fee0bc4](https://github.com/gocodebox/lifterlms/pull/2304/commits/fee0bc49621efeebc65d3692e7c6b9c6bbd3ff1c)
