### PR TITLE
Make sure to remove only custom caps from administrator role when rem…

### LINKED ISSUE #1352: Deleting the plugin when constant LLMS_REMOVE_ALL_DATA set to true results in site.domain/wp-admin/index.php to be not accessible
### Reproduction Steps

+ in your wp-config.php add `define( 'LLMS_REMOVE_ALL_DATA', true );` 
+ as admin disable LifterLMS and then delete it.
+ visit your side.domain/wp-admin/index.php

### Expected Behavior

+ I'd expect to be able to access that page without problems

### Actual Behavior

+ I see a white page with a WordPress message saying I'm not allowed to access that page

The problem should be here:
https://github.com/gocodebox/lifterlms/blob/4.4.4/uninstall.php#L41
so here, where the custom caps for the administrator role should be removed: https://github.com/gocodebox/lifterlms/blob/trunk/includes/class.llms.roles.php#L390
but actually we seem to remove all the role's caps:
https://github.com/gocodebox/lifterlms/blob/trunk/includes/class.llms.roles.php#L405

### Error Messages / Logs

```
"Sorry, you are not allowed to access this page."
```

### System and Environment Information

```
LifterLMS 4.4.4
WordPress 5.5.1
```

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information
HS-135912

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description
Fixes #1352 

## How has this been tested?
Manually, with existing unit tests, and updating the existing "remove roles" test.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: tests/phpunit/unit-tests/class-llms-test-roles.php [hunk 1]
```diff
@@ -65,24 +67,26 @@ public function test_install() {
 
 		$wp_roles = wp_roles();
 
-		// remove first
+		// Remove first.
 		LLMS_Roles::remove_roles();
-
-		// install them
+		add_filter( 'do_print', '__return_true' );
```
Comment (thomasplevy) [inline tests/phpunit/unit-tests/class-llms-test-roles.php]: What does this filter do? I cannot find it in the WP code ref or core code base (via manual searching)

File: includes/class.llms.roles.php [hunk 2]
```diff
@@ -387,22 +388,31 @@ public static function remove_roles() {
...
 	 */
-	private static function update_caps( $role, $type = 'add' ) {
+	private static function update_caps( $role, $type = 'add', $exclude_groups = array() ) {
+
+		$role_caps = self::get_all_caps( $role->name );
+		if ( ! empty( $exclude_groups ) ) {
+			foreach ( $exclude_groups as $exclude_group ) {
+				unset( $role_caps[ $exclude_group ] );
+			}
+		}
```
Comment (thomasplevy) [inline includes/class.llms.roles.php]: I think this can be written more succinctly (and by that I mean without having to run (essentially) the same loop twice by using a `continue` in the original loop.

```suggestion
```

File: includes/class.llms.roles.php [hunk 3]
```diff
@@ -387,22 +388,31 @@ public static function remove_roles() {
...
 
-		foreach ( self::get_all_caps( $role->name ) as $group => $caps ) {
+		foreach ( $role_caps as $group => $caps ) {
```
Comment (thomasplevy) [inline includes/class.llms.roles.php:411]:
```suggestion
		foreach ( self::get_all_caps( $role->name ) as $group => $caps ) {
		
			if ( in_array( $group, $exclude_groups, true ) ) {
				continue;
			}
		
```

**Review by thomasplevy — CHANGES_REQUESTED** [review]
I think we can remove double looping in the updated `update_caps()` method with the suggestions below

File: tests/phpunit/unit-tests/class-llms-test-roles.php (hunk 1 above)
Comment (eri-trabiccolo) [reply tests/phpunit/unit-tests/class-llms-test-roles.php]: ahah, that was for testing, sorry.

File: includes/class.llms.roles.php (hunk 2 above)
Comment (eri-trabiccolo) [reply includes/class.llms.roles.php]: well actually it's not running the same loop twice... and the idea was that in most of that cases with my code we make only 1 check, and if true (basically once, only when deleting the plugin), we run a for over 1 element.
With your suggestion below, we make a check for each group, and in most of the cases that check is useless.
So I chose ugliness+less_executions over succinctness.

If we want succinctness what about:
```php
$role_caps = self::get_all_caps( $role->name );
$role_caps = empty( $exclude_groups ) ? $role_caps : array_diff_key( $role_caps, array_flip( $exclude_groups ) );
```

what do you think?

File: tests/phpunit/unit-tests/class-llms-test-roles.php (hunk 1 above)
Comment (eri-trabiccolo) [reply tests/phpunit/unit-tests/class-llms-test-roles.php]: fixed in c661861

File: includes/class.llms.roles.php (hunk 2 above)
Comment (thomasplevy) [reply includes/class.llms.roles.php]: Sure that works too.

I just don't like the idea of a single function performing two similar loops when it doesn't have to.

Comment (eri-trabiccolo) [reply includes/class.llms.roles.php]: Ok I will probably go with the fancy `array_flip` one because it better feeds my ego.

Comment (eri-trabiccolo) [reply includes/class.llms.roles.php]: solved in 0779fe1

File: tests/phpunit/unit-tests/class-llms-test-roles.php [hunk 4]
```diff
@@ -65,24 +67,26 @@ public function test_install() {
...
 		$wp_roles = wp_roles();
 
-		// remove first
+		// Remove first.
 		LLMS_Roles::remove_roles();
 
-		// install them
+		// Install them.
 		LLMS_Roles::install();
+		remove_filter( 'do_print', '__return_true' );
```
Comment (thomasplevy) [inline tests/phpunit/unit-tests/class-llms-test-roles.php]:
```suggestion
		remove_filter( 'do_print', '__return_true' );
```

**Review by thomasplevy — CHANGES_REQUESTED** [review]
See suggestion to remove debug line and then we're good to go

File: tests/phpunit/unit-tests/class-llms-test-roles.php (hunk 4 above)
Comment (eri-trabiccolo) [reply tests/phpunit/unit-tests/class-llms-test-roles.php]: Ok this is stupid (I mean the fact that I left that), sorry.

Comment (eri-trabiccolo) [reply tests/phpunit/unit-tests/class-llms-test-roles.php]: fixed in 8ebca20
