### PR TITLE
Fix i18n dashboard language strings and allow customizing of permalink slugs

### LINKED ISSUE #2324: Language Change Not Abiding by User's Language on Backend
### Reproduction Steps

+ Found while looking into this ticket HS-211978
+ Install LifterLMS (and for contrast WooCommerce)
+ Set the site language to French and update.
+ Go into your user profile on the backend and change language to English for your account

### Expected Behavior

+ On the backend of the site the menu options should switch back to English (see the WooCommerce options)

### Actual Behavior

+ The LifterLMS menu options remain in French

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natie.myliftersite.com
Site Url: https://natie.myliftersite.com
Login Url: https://natie.myliftersite.com/wp-login.php
Version: 6.1.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 7.0.1
Db Version: 5.0.0
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+trial@lifterlms.com
Email From Name: My LifterLMS Trial Site
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.40
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.27
Software: Apache/2.4.54 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0


Theme
-------------------------------------------

Name: Twenty Seventeen
Version: 3.1
Themeuri: https://wordpress.org/themes/twentyseventeen/
Authoruri: https://wordpress.org/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 7.0.1
User Switching: 1.7.0
WooCommerce: 7.3.0
WP Mail Logging: 1.10.5


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

### LINKED ISSUE #2429: Conflict with Loco Translate plugin
### Reproduction Steps

Loco Translate can't find the translation file when the user has selected the "custom" location.
- Use Loco Translate to localize LifterLMS.
- Choose a custom location
https://share.getcloudapp.com/OAuoyPlm

### Expected Behavior

Loco should be able to correctly localize LiterLMS picking the translation file from the selected custom location.

### Actual Behavior

Loco Translate can't find the translation file when the user has selected the "custom" location.

Possible solution?
[from @dominiquemariano ]
When Loco Translate is installed, instead of looking at `wp-content/languages/lifterlms/lifterlms-en_US.mo`, we should look at `wp-content/languages/loco/plugins/lifterlms-en_US.mo` when the user selects a "custom" location

### System Information
```
LifterLMS 7.1.4
WordPress 6.2
Loco Translate 2.6.4
```

### This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Related User Information

https://wordpress.org/support/topic/loco-translate-not-working-as-expected/#post-16704935

### LINKED ISSUE #2525: Strings in libraries/lifterlms-blocks/assets/js/llms-blocks.js do not translate.
### Reproduction Steps

1. Install and activate `Loco Translate`.
2. Go to `WordPress Dashboard > Loco Translate > Plugins > LifterLMS > New Language`. Set `Choose a language: > WordPress language:` to `English (United States)`. And set `Choose a location:` to `Custom`.
3. Translate "**Courses**" (`Admin menu name`), to "**My Courses**". This works as you can see in [this video](https://share.zight.com/04udkdg7).
4. Now, translate ""**Course Information Options**" to "**My Course Information Options Test**". This does not work, as you can see in [this video](https://share.zight.com/Z4upzpqY).

### Expected Behavior
""**Course Information Options**" must be translatable, as well as other strings in `libraries/lifterlms-blocks/assets/js/llms-blocks.js` (_e.g._, `Display Estimated Time`, `Display Difficulty`, `Display Tracks`, _etc_)..

### Actual Behavior
""**Course Information Options**" did not translate. Other strings in `libraries/lifterlms-blocks/assets/js/llms-blocks.js` also did not translate (_e.g._, `Display Estimated Time`, `Display Difficulty`, `Display Tracks`, _etc_).

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### PR DESCRIPTION
**Pull request by brianhogg**
## Description

Various i18n fixes:

- Menu options in the WordPress admin should now show in the user's language
- Loads the text domain later to allow Loco Translate to change where translations are loaded from
- Set the slugs for courses, memberships and other core taxonomies to the current site language, and provide options to change them from Settings > Permalinks. This avoids slugs inadvertently changing if a user with access to flush the permalinks has a different language set than the site language.
- LifterLMS blocks in the Course editor and elsewhere now load translations, and are translatable via Loco Translate

Fixes #2324 
Fixes #2429 
Fixes #2525

## How has this been tested?

Manually. The current E2E doesn't permit tests before LifterLMS has been loaded, and switching languages was flaky.

## Screenshots 

Captura de pantalla 2024-02-16 a las 5 11 35 p  m
Block translations showing

Captura de pantalla 2024-02-16 a las 5 12 56 p  m
Menu options and notices showing in the user language rather than the site language (French in this case)

Captura de pantalla 2024-02-16 a las 5 21 54 p  m
Settings > Permalink options to modify LifterLMS permalink slugs. Shows field added via `lifterlms-assignments` add-on.

## Checklist:
- [x] This PR requires and contains at least one changelog file. 
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: class-lifterlms.php [hunk 1]
```diff
@@ -89,9 +82,9 @@ private function __construct() {
 		$this->query = new LLMS_Query();
 
 		// Hooks.
-		register_activation_hook( __FILE__, array( 'LLMS_Install', 'install' ) );
```
Comment (brianhogg) [inline class-lifterlms.php:92]: The `register_activation_hook` needs the main plugin filename. Since the class filename is being used here, this would never run. It's been moved into the main plugin file instead so the `verify_permalinks` runs on activation.

File: includes/class.llms.install.php [hunk 2]
```diff
@@ -613,6 +615,24 @@ public static function install() {
...
 
+	/**
+	 * Retrieve permalinks structure to verify if they are set, and any new defaults are saved
+	 *
+	 * @since [version]
+	 *
+	 * @return void
+	 */
+	public static function verify_permalinks() {
+		if ( ! get_option( 'lifterlms_permalinks' ) ) {
```
Comment (brianhogg) [inline includes/class.llms.install.php:626]: Perhaps this should always be run? If any add-ons have new defaults to set, they should be added in the site language immediately.

Comment (brianhogg) [reply includes/class.llms.install.php:626]: Switching to having add-ons handle their own saved option for the slug(s) they're changing, to avoid race conditions and decrease complexity.

That said, we may want to remove this condition since it's only run during install (plugin activation/update/install) and will ensure any defaults added in the future will have the correct default set based on the site language.

File: tests/phpunit/unit-tests/class-llms-test-assets.php [hunk 3]
```diff
@@ -723,64 +723,6 @@ public function test_register_script_undefined() {
...
 	}
 
-	/**
-	 * Test register_script() with translations
-	 *
-	 * @since 5.5.0
-	 *
-	 * @return void
-	 */
-	public function test_register_script_with_translations() {
```
Comment (brianhogg) [inline tests/phpunit/unit-tests/class-llms-test-assets.php:733]: From what I can see this test isn't testing what we want it to, since the translations are working as expected.
