### PR TITLE
Conditionally use the legacy default background image.

### LINKED ISSUE #2030: [6.0] Assigned Certificates are updated to new default image
### Reproduction Steps

+ In 5.x create a certificate and get it assigned to a user
+ Upgrade to 6.0
+ Go into LifterLMS->Reporting->Student->View previously assigned certificate

### Expected Behavior

+ The certificate will maintain the legacy settings from when it was assigned

### Actual Behavior

+ It is updated with the new default 6.0 template background (the content on the certificate remains the same)

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```

Wordpress
-------------------------------------------

Home Url: https://alleged-bug.myliftersite.com
Site Url: https://alleged-bug.myliftersite.com
Login Url: https://alleged-bug.myliftersite.com/wp-login.php
Version: 5.9.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0-beta.2
Db Version: 5.10.0
Course Catalog: Course Catalog (#16) [https://alleged-bug.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#17) [https://alleged-bug.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#19) [https://alleged-bug.myliftersite.com/dashboard/]
Checkout Page: Purchase (#18) [https://alleged-bug.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.15
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36


Theme
-------------------------------------------

Name: Twenty Twenty-Two
Version: 1.1
Themeuri: https://wordpress.org/themes/twentytwentytwo/
Authoruri: https://wordpress.org/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.0.0-beta.2
WP Rollback: 1.7.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------



```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

### PR DESCRIPTION
**Pull request by pondermatic**
## Description

1. Added setting the `lifterlms_has_legacy_achievements` option to 'yes' during an update to LifterLMS 6.0.0 if there are any achievement templates or awarded achievements that use the default background image.
2. Changed `LLMS_Test_Trait_Award_Default_Images::test_get_default_default_image_src()`.
    1. All achievements use the old default image if the `lifterlms_has_legacy_achievements` option is 'yes', else the new default image is used.
    2. Version 1 certificates use the old default image if the `lifterlms_has_legacy_certificates` option is 'yes', else the new default image is used.
    3. Version 2 certificates always use the new default image.

Fixes #2030.

## How has this been tested?
Manually and with unit  tests.
1. Install LifterLMS 5.
2. Create achievement and certificate templates that use the default background.
3. Create achievement and certificate templates that use a custom background.
4. Award an achievement and a certificate.
5. Upgrade to LifterLMS 6.
6. View legacy templates and awards.
7. Create a new certificate template.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: includes/functions/updates/llms-functions-updates-600.php [hunk 1]
```diff
@@ -208,15 +215,19 @@ function _migrate_awards( $type ) {
 	// Don't trigger save hooks.
 	remove_action( "save_post_llms_my_{$type}", array( 'LLMS_Controller_Awards', 'on_save' ), 20 );
 
-	$legacy_option_added = false;
+	$legacy_certificates_option_added = false;
+	$legacy_achievements_option_added = false;
```
Comment (eri-trabiccolo) [inline includes/functions/updates/llms-functions-updates-600.php]: the whole method runs `once` per `$type` right?
So we don't need to keep track of both these _additions_ or differentiate between achievements and certificates here. Not anymore. So:
```suggestion
	$legacy_option_added = false;
```

File: includes/functions/updates/llms-functions-updates-600.php [hunk 2]
```diff
@@ -208,15 +215,19 @@ function _migrate_awards( $type ) {
...
 
-		if ( 'certificate' === $type && ! $legacy_option_added ) {
-			_add_legacy_opt();
-			$legacy_option_added = true;
+		if ( 'certificate' === $type && ! $legacy_certificates_option_added ) {
+			_add_legacy_opt( $type );
+			$legacy_certificates_option_added = true;
+		} elseif ( 'achievement' === $type && ! $legacy_achievements_option_added ) {
+			_add_legacy_opt( $type );
+			$legacy_achievements_option_added = true;
```
Comment (eri-trabiccolo) [inline includes/functions/updates/llms-functions-updates-600.php]:
```suggestion
		if ( ! $legacy_option_added ) {
			_add_legacy_opt( $type );
			$legacy_option_added = true;
```

File: includes/functions/updates/llms-functions-updates-600.php [hunk 3]
```diff
@@ -81,15 +81,22 @@ function migrate_award_templates() {
...
-			$legacy_option_added = true;
+
+			if ( ! $legacy_achievements_option_added ) {
+				_add_legacy_opt( 'achievement' );
+				$legacy_achievements_option_added = true;
+			}
+		} elseif ( 'llms_certificate' === $post->post_type && ! $legacy_certificates_option_added ) {
+			_add_legacy_opt( 'certificate' );
+			$legacy_certificates_option_added = true;
 		}
```
Comment (eri-trabiccolo) [inline includes/functions/updates/llms-functions-updates-600.php]: This code can be refactored a bit and be like:
```php
			$type = llms_strip_prefixes( $post->post_type );
			_migrate_image( $post->ID, $type );
			if ( 'achievement' === $type ) {
				_migrate_achievement_content( $post->ID );
			}
			if ( ! ${"legacy_{$type}s_option_added"} ) {
				_add_legacy_opt( $type );
				${"legacy_{$type}s_option_added"} = true;
			}
```
but usually @thomasplevy doesn't like this stuff, I find it more readable: less if, less nested if.

File: includes/traits/llms-trait-award-default-images.php [hunk 4]
```diff
@@ -30,13 +30,31 @@ trait LLMS_Trait_Award_Default_Images {
...
 	 */
 	protected function get_default_default_image_src() {
 
-		$img = "default-{$this->award_type}.png";
+		$img        = "default-{$this->award_type}.png";
+		$use_legacy = false;
+
+		switch ( $this->award_type ) {
+			case 'achievement':
+				$use_legacy = 'yes' === get_option( 'lifterlms_has_legacy_achievements', 'no' );
```
Comment (eri-trabiccolo) [inline includes/traits/llms-trait-award-default-images.php]: we can also use [`llms_parse_bool`](https://developer.lifterlms.com/reference/functions/llms_parse_bool/).
```suggestion
				$use_legacy = llms_parse_bool( get_option( 'lifterlms_has_legacy_achievements', 'no' ) );
```

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
Aside from the minor changes requested I'm not sure about the choice here.
Let me explain...
We then decided that the achievement's default image works a bit different than the certificate's one:
- old certificates using the old default images will keep on using it, unless they're migrated to template v2.
- if there's at least an old achievement - no matter if it defined an image, - all the achievements old and new which use the default image will use the old default img. If users change the default image option, both old and new achievements will use the new default img. 

I think I'm fine with this last part but I think, but I think that we have to change the way we determine whether or not an achievement is legacy during the update. I think that the condition must be that it has not image set. At least for our purpose that is a legacy achievement. Am I wrong?
what do you think @gocodebox/engineering ?

File: includes/functions/updates/llms-functions-updates-600.php (hunk 1 above)
Comment (pondermatic) [reply includes/functions/updates/llms-functions-updates-600.php]: Good catch.

File: includes/functions/updates/llms-functions-updates-600.php (hunk 3 above)
Comment (pondermatic) [reply includes/functions/updates/llms-functions-updates-600.php]: I like everything except `${"legacy_{$type}s_option_added"}`, which is very clever, but a little hard to read and my IDE thinks that `$legacy_certificates_option_added` is never used. So instead, I did this:
```php
	$legacy_option_added['achievement'] = false;
	$legacy_option_added['certificate'] = false;

	foreach ( $query->posts as $post ) {

		$type = llms_strip_prefixes( $post->post_type );
		_migrate_image( $post->ID, $type );

		if ( 'achievement' === $type ) {
			_migrate_achievement_content( $post->ID );
		}

		if ( ! $legacy_option_added[ $type ] ) {
			_add_legacy_opt( $type );
			$legacy_option_added[ $type ] = true;
		}
	}
```

File: includes/traits/llms-trait-award-default-images.php (hunk 4 above)
Comment (pondermatic) [reply includes/traits/llms-trait-award-default-images.php]: Nice!

**Comment by pondermatic** [comment]
@eri-trabiccolo wrote,
> I think that we have to change the way we determine whether or not an achievement is legacy during the update. I think that the condition must be that it has not image set. At least for our purpose that is a legacy achievement. Am I wrong?

That is a good point. During the update, if all achievements are using custom images, then we **do not** want to set the `lifterlms_has_legacy_achievements` option. I also think that this same rule should be applied to certificates.

File: includes/functions/updates/llms-functions-updates-600.php (hunk 3 above)
Comment (eri-trabiccolo) [reply includes/functions/updates/llms-functions-updates-600.php]: yeah an array would work too, I guess :P 
Although I kinda like `${"legacy_{$type}s_option_added"}` too, but I guess this is a problem of mine, I'm sure Thomas doesn't like it as well, so I'm a minority :D

**Comment by eri-trabiccolo** [comment]
> @eri-trabiccolo wrote,
> 
> > I think that we have to change the way we determine whether or not an achievement is legacy during the update. I think that the condition must be that it has not image set. At least for our purpose that is a legacy achievement. Am I wrong?
> 
> That is a good point. During the update, if all achievements are using custom images, then we **do not** want to set the `lifterlms_has_legacy_achievements` option. I also think that this same rule should be applied to certificates.

About certificates, the thing is that the only existence of a certificate qualifies them as legacy, because for certificates being legacy means "created with the classic editor", while achievements are still created with the classic editor...

**Comment by pondermatic** [comment]
@eri-trabiccolo wrote,
> About certificates, the thing is that the only existence of a certificate qualifies them as legacy, because for certificates being legacy means "created with the classic editor", while achievements are still created with the classic editor...

Right. However, when a site is updated to LifterLMS 6.0, if all achievements use a custom image, then we don't want to set the `lifterlms_has_legacy_achievements` option because new achievements should use the new default image.

**Comment by eri-trabiccolo** [comment]
> @eri-trabiccolo wrote,
> 
> > About certificates, the thing is that the only existence of a certificate qualifies them as legacy, because for certificates being legacy means "created with the classic editor", while achievements are still created with the classic editor...
> 
> Right. However, when a site is updated to LifterLMS 6.0, if all achievements use a custom image, then we don't want to set the `lifterlms_has_legacy_achievements` option because new achievements should use the new default image.

That's what I'm saying :D 
But you said:
> I also think that this same rule should be applied to certificates. 

~And I don't agree with this, because of what I said above :D Certificates are different.~ (see below)

**Comment by eri-trabiccolo** [comment]
Oh, I changed my mind @pondermatic  :D
I think you're right, we actually use the `llms_has_legacy_certificates` only in the settings to decide whether or not showing legacy certificates settings, which actually only refer to the legacy background. So I propose to use a more _descriptive_ name for this option which could be `lifterlms_has_legacy_{$engagement_type}s_background` or something similar, so that it will help us to recall what those options are for.
What do you think @gocodebox/engineering

File: includes/functions/updates/llms-functions-updates-600.php [hunk 5]
```diff
@@ -81,15 +81,21 @@ function migrate_award_templates() {
 		)
 	);
 
-	$legacy_option_added = false;
+	$legacy_option_added['achievement'] = false;
+	$legacy_option_added['certificate'] = false;
```
Comment (eri-trabiccolo) [inline includes/functions/updates/llms-functions-updates-600.php:85]:
```suggestion
	$legacy_option_added = array(
		'achievement' => false,
		'certificate' => false,
	);
```
is it any better or not, dunno...

File: includes/traits/llms-trait-award-default-images.php [hunk 6]
```diff
@@ -30,13 +30,31 @@ trait LLMS_Trait_Award_Default_Images {
...
+		$use_legacy = false;
+
+		switch ( $this->award_type ) {
+			case 'achievement':
+				$use_legacy = llms_parse_bool( get_option( 'lifterlms_has_legacy_achievements', 'no' ) );
+				break;
+			case 'certificate':
+				$certificate = llms_get_certificate( null, true );
+				if ( $certificate && 1 === $certificate->get_template_version() ) {
+					$use_legacy = 'yes' === get_option( 'lifterlms_has_legacy_certificates', 'no' );
```
Comment (eri-trabiccolo) [inline includes/traits/llms-trait-award-default-images.php]:
```suggestion
					$use_legacy = llms_parse_bool( get_option( 'lifterlms_has_legacy_certificates', 'no' ) );
```

File: includes/functions/updates/llms-functions-updates-600.php (hunk 5 above)
Comment (pondermatic) [reply includes/functions/updates/llms-functions-updates-600.php:85]: I first did it that way. It allows us to easily add more elements. Except, we aren't going to add any more engagement types in the 6.0 update functions and it uses 4 lines instead of 2.

Comment (eri-trabiccolo) [reply includes/functions/updates/llms-functions-updates-600.php:85]: I don't know, for some reason I feel `=array(a,b,c)` resembles a variable declaration.

**Comment by pondermatic** [comment]
@eri-trabiccolo wrote,
> Oh, I changed my mind @pondermatic :D
> I think you're right, we actually use the `llms_has_legacy_certificates` only in the settings to decide whether or not showing legacy certificates settings, which actually only refer to the legacy background. So I propose to use a more _descriptive_ name for this option which could be `lifterlms_has_legacy_{$engagement_type}s_background` or something similar, so that it will help us to recall what those options are for.

According to [this comment in `llms_strip_prefixes()`](https://github.com/gocodebox/lifterlms/blob/dev-600/includes/llms.functions.core.php#L1166), we should use the `llms_` prefix instead of `lifterlms_`. 

I'm not sure `background` is a good word to use since achievements aren't displayed with text on the image.

How about `llms_use_legacy_achievement_default_image` and `llms_use_legacy_certificate_default_image`?

EDIT: It's also used to enable the "Legacy Certificate Background Image Settings" on the engagements settings page.

**Comment by eri-trabiccolo** [comment]
@pondermatic wrote:
> According to [this comment in `llms_strip_prefixes()`](https://github.com/gocodebox/lifterlms/blob/dev-600/includes/llms.functions.core.php#L1166), we should use the `llms_` prefix instead of `lifterlms_`.

I'm not sure about this, Thomas might have chosen `lifterlms_` b/c of the legacy certificate settings ([here](https://github.com/gocodebox/lifterlms/blob/dev-600/includes/admin/settings/class.llms.settings.engagements.php)) were using that prefix, for homogeneity...? dunno.
 
> I'm not sure `background` is a good word to use since achievements aren't displayed with text on the image.

You're right, image is better.

> How about `llms_use_legacy_achievement_default_image` and `llms_use_legacy_certificate_default_image`?

What I want to have here is an option name that describes the state of the system, that brought to setting it, rather than a name that tells what the system is going to do, because the latter can change, I don't want to mess concepts.
What about?
`llms_has_{$type}s_with_legacy_default_image`

But let's not stuck on this, let's choose one :D

**Comment by pondermatic** [comment]
> What about?
> `llms_has_{$type}s_with_legacy_default_image`

I like it. It's a little long, but an accurate description.

**Review by eri-trabiccolo — APPROVED** [review]

**Comment by thomasplevy** [comment]
Nice work @pondermatic  <3
