### PR TITLE
v4.5.1: Dev to Trunk

### LINKED ISSUE #1096: Change the currency in sales reporting tab
### Reproduction Steps
Change your currency to something else apart from Dollars
Go to Reporting >> Sales
It still stays at Dollars
image

### Expected Behavior
Supposed to change the currency to the currency in settings

### Actual Behavior

Still remains at Dollars

### LINKED ISSUE #1122: Post Excerpt doesn't get updated(either deleted or removed)
### Reproduction Steps

Open up a course.
Type an excerpt to the right sidebar(not the one below the editor)
Click on update. 

### Expected Behavior

Meant to either remove or update to the latest excerpt on it

### Actual Behavior

If there was an excerpt before, it won't get deleted and if there was none before and you add one, it'll get deleted

### Error Messages / Logs

HS-119283
https://www.loom.com/share/898e1d74d43d41578fa42084520befa0

### LINKED ISSUE #1311: JS Front End: LLMS.Achievements initialized even if there are no achievements.
This is not a real issue as it doesn't really produce any actual issue, although the condition is not correct:
https://github.com/gocodebox/lifterlms/blob/cadf4217a1f648e0b6020cf1ce1cad72a9db99fb/assets/js/app/llms-achievements.js#L21

It should be:
```js
if ( $( '.llms-achievement' ).length ) { 
```

### LINKED ISSUE #1352: Deleting the plugin when constant LLMS_REMOVE_ALL_DATA set to true results in site.domain/wp-admin/index.php to be not accessible
### Reproduction Steps

+ in your wp-config.php add `define( 'LLMS_REMOVE_ALL_DATA', true );` 
+ as admin disable LifterLMS and then delete it.
+ visit your side.domain/wp-admin/index.php

### Expected Behavior

+ I'd expect to be able to access that page without problems

### Actual Behavior

+ I see a white page with a WordPress message saying I'm not allowed to access that page

The problem should be here:
https://github.com/gocodebox/lifterlms/blob/4.4.4/uninstall.php#L41
so here, where the custom caps for the administrator role should be removed: https://github.com/gocodebox/lifterlms/blob/trunk/includes/class.llms.roles.php#L390
but actually we seem to remove all the role's caps:
https://github.com/gocodebox/lifterlms/blob/trunk/includes/class.llms.roles.php#L405

### Error Messages / Logs

```
"Sorry, you are not allowed to access this page."
```

### System and Environment Information

```
LifterLMS 4.4.4
WordPress 5.5.1
```

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information
HS-135912

### LINKED ISSUE #1365: [wp-admin] List courses: Mine always shows zero, click it go to list of Posts instead of Courses
### Reproduction Steps

+ Include clear and detailed step by step instructions on how the issue can be reliably reproduced

1. Setup just another WordPress.
2. Install LifterLMS plugin.
3. Create a sample course.
4. In Admin Dashboard, go to Courses > Courses to view list of courses.

+ Include screenshots where applicable
image

### Expected Behavior

+ Include a concise description of what you expected to happen (but didn't)

"Mine" should be 1.
Click to "Mine" should stay til in Courses > Courses.

### Actual Behavior

+ Include a concise description of what actually happens (but isn't supposed to)

"Mine" is 0.
Click "Mine" jump to Posts > All Posts.

### System and Environment Information

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### LINKED ISSUE #1368: Remove "view as" from Admin bar when not logged in with a role with the right capability
### Reproduction Steps

On your LifterLMS site, install a plugin like BuddyPress or any plugin or theme that allows you to show the wp-admin bar to visitors.
You will see the "View as" because it's attached to wp-admin bar

### Expected Behavior

It shouldn't show for visitors and users without the right capability

### Actual Behavior

It shows for users and visitors

### Error Messages / Logs

+ Include any relevant error messages or log files
```
N/A

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
System Report:
Wordpress
-------------------------------------------

Home Url: https://zodianz.com
Site Url: https://zodianz.com
Login Url: https://zodianz.com/wp-login.php
Version: 5.5.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Zodianz Zodiac Signs -home (#68528) [https://zodianz.com/]
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.5.0
Db Version: 4.4.4
Course Catalog: Course Catalog (#22570) [https://zodianz.com/courses/]
Membership Catalog: Not Set
Student Dashboard: My Courses (#22573) [https://zodianz.com/?page_id=22573]
Checkout Page: Purchase (#22572) [https://zodianz.com/?page_id=22572]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 0
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: yes
Terms Page: Returns, Exchanges, and Refunds (#667) [https://zodianz.com/returns-exchanges-refunds/]
Checkout Names: required
Checkout Address: hidden
Checkout Phone: hidden
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: yes
Account Names: required
Account Address: optional
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: orders@zodianz.com
Email From Name: Zodianz
Email Footer Text: Copyright 2018 | Zodianz LLC. | Anaheim, CA 92801 | Instructor Joan Zodianz
Email Header Image:
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.26
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 3000
Php Max Upload Size: 128 MB
Php Memory Limit: 768M
Php Post Max Size: 128M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 120
Php Version: 7.3.20
Software: Apache
Wp Memory Limit: 768M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36


Theme
-------------------------------------------

Name: Beaver Builder Child Theme
Version: 1.0
Themeuri: http://www.wpbeaverbuilder.com
Authoruri: http://www.fastlinemedia.com
Template: bb-theme
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Advanced Cron Manager: 2.4.0
Advanced Floating Content: 3.6.7
bbP private groups: 3.8.4
bbPress: 2.6.5
Beaver Builder Plugin (Pro Version): 2.4.0.5
Bookly: 18.8
Bookly Customer Cabinet (Add-on): 3.1
Bookly Pro (Add-on): 3.0
Bookly Ratings (Add-on): 2.1
Bookly Service Schedule (Add-on): 2.5
Bookly Special Days (Add-on): 3.7
Bookly Staff Cabinet (Add-on): 3.2
Booster for WooCommerce: 5.3.4
BuddyPress: 6.3.0
BuddyPress Clear Notifications: 1.0.4
BuddyPress Lock: 1.3.0
Classic Editor: 1.6
Code Snippets: 2.14.0
Coupon Referral Program: 1.5.0
Easy Table of Contents: 2.0.11
Envato Market: 2.0.5
Google Analytics for WordPress by MonsterInsights: 7.12.3
Heartbeat Control by WP Rocket: 2.0
iFlyChat: 4.6.4
LifterLMS: 4.5.0
LifterLMS Customizations: 1.0.0
LifterLMS Helper: 3.1.0
LifterLMS Labs: 1.5.3
LifterLMS WooCommerce: 2.1.2
MagiCards: 2.0.5
MailChimp for WooCommerce Memberships: 1.3.1
ManageWP - Worker: 4.9.7
Marvelous Hover for Wordpress: 2.0.7
Max Mega Menu: 2.9.1
Max Mega Menu - Pro Addon: 2.1.3
Members: 3.1.3
myCred: 1.8.14
myCRED WooCommerce Plus - WooCommerce: 1.7.2
Photo Gallery: 1.5.62
Product Filter for WooCommerce: 7.2.9
PW WooCommerce Gift Cards Pro: 1.251
RafflePress Pro: 1.3.8
Rank Math SEO: 1.0.48.2
Resend Welcome Email: 1.1.9
Reveal IDs: 1.5.4
SG Optimizer: 5.6.7
Slider Revolution: 6.2.23
Slider Revolution 404 Page Add-On: 2.0.0
Slider Revolution Featured Slider Add-on: 2.0.1
Slider Revolution Particles Effect: 2.2.6
Stachethemes Event Calendar: 3.1.5
Super Socializer: 7.13.2
Vimeography: 2.1.1
Vimeography Developer Bundle: 2.1.1
Vimeography Pro: 2.0.3
WooCommerce: 4.5.2
WooCommerce AvaTax: 1.10.4
Woocommerce Blocker: 1.8.7
WooCommerce First Data Payeezy Gateway: 4.8.1
WooCommerce Google Product Feed: 9.1.2
WooCommerce Memberships: 1.19.1
WooCommerce Shipment Tracking: 1.6.25
WooCommerce Subscription Downloads: 1.1.29
WooCommerce Subscriptions: 3.0.9
WooSwipe: 1.1.8.9
Wordfence Security: 7.4.11
WP Mail SMTP: 2.4.0
Youzer: 2.6.1
Youzer - Buddypress Block Members: 1.0.0
ZodiacPress: 2.0.3


Integrations
-------------------------------------------

BbPress: No
BuddyPress: Yes
WooCommerce: Yes


Template Overrides
-------------------------------------------

```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)
HS-137254

### LINKED ISSUE #1369: Warnings from jQuery Migrate helper
### Reproduction Steps

Install and activate the plugin: [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/)
Go to LifterLMS >> Settings and see the Warning as shown in the screenshot:
image

### Expected Behavior

Remove deprecated code

### Actual Behavior

Still has deprecated code

### Error Messages / Logs

+ Include any relevant error messages or log files
```
N/A

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
System Report:
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.5.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_CA
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#5) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.5.0
Db Version: 4.5.0
Course Catalog: Online Courses (#328) [[removed]/course-information/courses/]
Membership Catalog: Memberships (#3046) [[removed]/course-information/membership-catalog/]
Student Dashboard: My Dashboard (#331) [[removed]/dashboard/]
Checkout Page: Checkout Purchases (#330) [[removed]/dashboard/checkout/]
Course Catalog Per Page: 2
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: yes
Terms Page: Terms and Conditions (#663) [[removed]/dashboard/terms-and-conditions/]
Checkout Names: required
Checkout Address: required
Checkout Phone: required
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: required
Registration Phone: required
Registration Voucher: optional
Registration Email Confirmation: yes
Account Names: required
Account Address: required
Account Phone: required
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: CA
Currency: CAD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: [removed]
Email Header Image: 425
Cert Bg Width: 720
Cert Bg Height: 577
Cert Legacy Compat: yes


Gateways
-------------------------------------------

PayPal: Enabled
PayPal Test Mode: Disabled
PayPal Logging: no
PayPal Order: 1
Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 3000
Php Max Upload Size: 24 MB
Php Memory Limit: 256M
Php Post Max Size: 24M
Php Soap: No
Php Suhosin: No
Php Time Limt: 150
Php Version: 7.4.11
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0


Theme
-------------------------------------------

Name: Astra
Version: 2.5.5
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/
Template:
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

Accessibility by UserWay: 1.2
Advanced Database Cleaner: 3.0.3
Akismet Anti-Spam: 4.1.6
All In One WP Security: 4.4.4
Anti-Malware Security and Brute-Force Firewall: 4.19.69
Better Search Replace: 1.3.3
Broken Link Checker: 1.11.14
Contact Form 7: 5.2.2
Cookie Notice: 1.3.2
Definitely allow mobile zooming: 1.4
Display Environment Type: 1.3
Duplicate TEC Event: 1.5.2
Email Log: 2.4.3
Enable jQuery Migrate Helper: 1.0.1
Events Shortcodes and Templates Addon: 1.5.3
Event Tickets: 5.0.1
Event Tickets/Eventbrite Extension: Show Cost Field: 1.0.1
GTranslate: 2.8.60
HTML5 Responsive FAQ: 2.8.5
LifterLMS: 4.5.0
LifterLMS Advanced Quizzes: 1.1.0
LifterLMS Helper: 3.1.0
LifterLMS Labs: 1.5.3
LifterLMS PayPal Gateway: 1.3.0
Login-Logout: 3.8
Log Out Shortcode: 1.0.8
Meta Tag Manager: 2.1.2
Rank Math SEO: 1.0.48.2
Shortcode For Current Date: 2.1.2
Shortcoder: 5.3.2
Simple Social Icons: 3.0.2
The Events Calendar: 5.2.0
The Events Calendar Extension: Events Control: 1.0.0
The Events Calendar Shortcode & Block: 2.4
Ultimate Addons for Gutenberg: 1.17.0
UpdraftPlus - Backup/Restore: 1.16.29
WP Content Copy Protection with Color Design: 2.2.7
WP GDPR Compliance: 1.5.4
WP Super Cache: 1.7.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------


```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)
HS-137303

### LINKED ISSUE #1376: PHP notice logged, when navigating the backend and Yoast SEO plugin active
### Reproduction Steps

+ Install and activate the Yoast SEO plugin
+ Make sure you enabled the PHP error debug logging
+ Navigate the WordPress backend
+ Check the log

### Expected Behavior

+ No warnings/errors logged

### Actual Behavior

+ Warning logged

### Error Messages / Logs

```
[14-Oct-2020 10:21:18 UTC] PHP Notice:  Undefined index: post_type in /srv/www/wordpress-two/public_html/wp-content/plugins/lifterlms/includes/admin/post-types/post-tables/class.llms.admin.post.table.lessons.php on line 160

```

### System and Environment Information

```
LifterLMS: 4.5.0
Yoast SEO: 15.1
```

### This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### User Related Information
This is something, not explicitly reported, but that I noticed first here:
https://wordpress.org/support/topic/something-went-wrong-error-when-saving-in-settings-tab/#post-13513107
(see the log linked in that comment)

Then investigating a little bit I was able to link it to the use of Yoast SEO, and been able to reproduce the bug. 
@nrherron92  was able to reproduce it too.

### PR DESCRIPTION
**Pull request by thomasplevy**
+ Fixes #1122 via PR #1375 
+ Fixes #1096 via PR #1371 
+ Fixes #1311 via #1378 (thanks @imknight)
+ Fixes #1352 via PR #1362 
+ Fixes #1365 via PR #1367 (thanks @nhandl3!)
+ Fixes #1368 via PR #1371 
+ Fixes #1369 via PR #1374 
+ Fixes #1376 via PR #1377 
+ Includes PR #1370 (Initial work for #933)

### CODE REVIEW

File: tests/phpunit/unit-tests/functions/class-llms-test-functions-user-postmeta.php [hunk 1]
```diff
@@ -74,7 +85,7 @@ public function test_delete_user_postmeta() {
 			$i++;
 		}
 		$this->assertTrue( llms_delete_user_postmeta( $this->student_id, $this->course_id, '_test_data_to_erase', 'eraseme3' ) );
-		$this->assertEquals( array( 'eraseme1', 'eraseme2' ), llms_get_user_postmeta( $this->student_id, $this->course_id, '_test_data_to_erase', false ) );
+		$this->assertEqualSets( array( 'eraseme1', 'eraseme2' ), llms_get_user_postmeta( $this->student_id, $this->course_id, '_test_data_to_erase', false ) );
```
Comment (eri-trabiccolo) [inline tests/phpunit/unit-tests/functions/class-llms-test-functions-user-postmeta.php:88]: TIL

Comment (thomasplevy) [reply tests/phpunit/unit-tests/functions/class-llms-test-functions-user-postmeta.php:88]: it's from the WP Core test lib: https://github.com/WordPress/wordpress-develop/blob/1ec9dc6fa46b23f7724dfa3f057e2da1a1dd3133/tests/phpunit/includes/abstract-testcase.php#L705

There's actually quite a few helpful assertions in the class. If you want homework, study them!
