### PR TITLE
asset handler class and tests

### LINKED ISSUE #1274: Core assets loaded with technically invalid URI
### Reproduction Steps

Seems there's a double slash in this file wp-content/plugins/lifterlms//assets/js/llms.min.js?ver=4.2.0

### Expected Behavior

Should be one /

### Actual Behavior

Double /
I also see this was fixed here: #598 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
N/A

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Home Url: https://generousmarriage.com
Site Url: https://generousmarriage.com
Login Url: https://generousmarriage.com/wp-login.php
Version: 5.4.2
Debug Mode: Yes
Debug Log: Yes
Debug Display: No
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: home (#16) [https://generousmarriage.com/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.2.0
Db Version: 4.2.0
Course Catalog: Course Catalog (#1108) [https://generousmarriage.com/courses/]
Membership Catalog: Membership Catalog (#1109) [https://generousmarriage.com/memberships/]
Student Dashboard: Dashboard (#1111) [https://generousmarriage.com/dashboard/]
Checkout Page: Purchase (#1110) [https://generousmarriage.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: hidden
Checkout Phone: hidden
Checkout Email Confirmation: no
Open Registration: no
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: hidden
Account Phone: hidden
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team@generousmarriage.com
Email From Name: The Generous Marriage Podcast
Email Footer Text:
Email Header Image:
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Gateways
-------------------------------------------

PayPal: Enabled
PayPal Test Mode: Disabled
PayPal Logging: no
PayPal Order: 1
Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: no
Stripe Order: 1
Manual: Disabled
Manual Logging:
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.6.40
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 3000
Php Max Upload Size: 128 MB
Php Memory Limit: 768M
Php Post Max Size: 128M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 120
Php Version: 7.3.16
Software: Apache
Wp Memory Limit: 1024


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36


Theme
-------------------------------------------

Name: Divi Child Theme
Version:
Themeuri: https://generousmarriage.com/
Authoruri: https://generousmarriage.com/
Template: Divi
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Better Search Replace: 1.3.3
Blubrry PowerPress: 8.3.4
Classic Editor: 1.5
Embed Any Document: 2.6.1
Enable Media Replace: 3.4.1
Jetpack by WordPress.com: 8.7.1
LifterLMS: 4.2.0
LifterLMS Advanced Videos: 1.0.0-beta.8
LifterLMS Helper: 3.1.0
LifterLMS Labs: 1.5.3
LifterLMS MailChimp Add-on: 3.1.2
LifterLMS PayPal Gateway: 1.3.0
LifterLMS Stripe Payment Gateway: 5.2.0
LifterLMS WooCommerce: 2.1.1
Loco Translate: 2.4.0
Mailchimp for WooCommerce: 2.4.1
Pretty Links: 3.1.1
reSmush.it Image Optimizer: 0.3.10
SumoMe: 1.31
WooCommerce: 4.3.1
WooCommerce PayPal Checkout Gateway: 2.0.3
WooCommerce Stripe Gateway: 4.5.0
WooCommerce Subscriptions: 3.0.5
Wordfence Security: 7.4.9
WordPress Importer: 0.7
WordPress User Notes: 1.4.3
WP File Manager: 6.5
WP Rocket: 3.6.2.1
Yoast SEO: 14.6.1
Zivi Kivi: 1.0.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
WooCommerce: Yes
LifterLMS MailChimp: Yes
Videos: Vimeo: Yes
Videos: Wistia: No
Videos: YouTube: No


Template Overrides
-------------------------------------------

```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)
HS-130099

### LINKED ISSUE #1285: PHP 7.3 compat: Deprecation warning using non-string needles for str(i)pos()
### Reproduction Steps
Not sure how this can actually happen, but I could reproduce it by forcing a condition:
```
add_filter(
	'login_url',
	'__return_empty_string'
);
```

### Expected Behavior

+ No error/warning logged

### Actual Behavior

+ Deprecation warning logged

Actually the user says it happens when switched from PHP 7.3 to 7.4, but this deprecation has been introduced in 7.3
https://wiki.php.net/rfc/deprecations_php_7_3#string_search_functions_with_integer_needle

### Error Messages / Logs

```
PHP Deprecated:  stripos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /srv/www/wordpress-one/public_html/wp-content/plugins/lifterlms/includes/class.llms.ajax.php on line 130
```

### System and Environment Information
customer's one:
```

System Report:
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url:
Version: 5.4.2
Debug Mode: Yes
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#4) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.3.1
Db Version: 4.3.1
Course Catalog: Not Set
Membership Catalog: Not Set
Student Dashboard: Student Dashboard (#270) [[removed]/student-dashboard/]
Checkout Page: Not Set
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: optional
Checkout Phone: optional
Checkout Email Confirmation: no
Open Registration: no
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: optional
Account Phone: optional
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: yes
Recurring Payments: no
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image:
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: yes


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging:
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 128 MB
Php Memory Limit: 256M
Php Post Max Size: 128M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 300
Php Version: 7.4.9
Software: nginx/1.17.10
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36


Theme
-------------------------------------------

Name: MOP Divi child
Version: 1.0.0
Themeuri: https://elegantthemes.com
Authoruri:
Template: Divi
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Advanced Custom Fields: 5.8.13
AffiliateWP: 2.5.6
All In One WP Security: 4.4.4
Autocomplete WooCommerce Orders: 1.3.1
Change Quantity on Checkout for WooCommerce: 1.0
Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: 5.1.3
Cookie Notice: 1.3.2
Duplicate Page: 4.2
Easy Social Sharing: 1.3.3
ES Woocommerce ActiveCampaign: 1.9.15
Gravity Forms: 2.4.20
If Menu - Visibility control for menu items: 0.16.1
Imagify: 1.9.10
InfiniteWP - Client: 1.9.4.6
LifterLMS: 4.3.1
LifterLMS WooCommerce: 2.0.11
MOP Like Button: 1.0.0
MOP Restrict: 1.0.0
MOP User Photos: 1.0.0
PixelYourSite PRO: 7.6.1
Really Simple SSL: 3.3.4
reCaptcha for WooCommerce: 1.0.14
Redirection: 4.8
WooCommerce: 4.3.1
WooCommerce Cart Abandonment Recovery: 1.2.7
WooCommerce Checkout Field Editor: 1.5.35
WooCommerce PDF Product Vouchers: 3.7.8
WooCommerce Price Based on Country (Basic): 2.0.10
WooCommerce Stripe Gateway: 4.5.0
Woo Discount Rules: 2.0.2
WordPress Importer: 0.7
wpDiscuz: 7.0.7
WP File Manager: 6.5
WP Migrate DB Pro: 1.9.12
WP Rocket: 3.6.3
YITH WooCommerce Customize My Account Page: 2.6.4
Yoast SEO: 14.7


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
WooCommerce: Yes


Template Overrides
-------------------------------------------

content-certificate.php (ver: 3.18.0): /www/mastersofphotography_809/public/wp-content/themes/mop-divi-child/lifterlms/ (ver: 3.18.0)
course/lesson-navigation.php (ver: ): /www/mastersofphotography_809/public/wp-content/themes/mop-divi-child/lifterlms/ (ver: )
```

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information

HS-130663

### PR DESCRIPTION
**Pull request by thomasplevy**
## Description

Fixes #1274
Fixes #1285

Adds an "API" (that's derivative of the the WP Core's asset dependency API) which can be used to simplify asset registration within LifterLMS (and LifterLMS add-ons).

The goal of this class is to reduce the amount of redundant code that needs to be written to load assets.

All assets are defined in a definition list (this PR includes a small number of assets to demonstrate the concept; later we can move all asset definitions to this list).

When an asset needs to be registered or enqueued it will still be registered via the WP Core methods/api but our derivitive API will make it so that we only ever have to define things like asset versions (for all assets that share a version with the LifterLMS Core) and plugin url one time.

Then we will register the asset by handle.

## How has this been tested?

+ New unit tests have been written to cover all new code (I think it's 100% coverage if not pretty darn close, CC will tell us soon enough).
+ Manually tested using these methods in favor of the WP core directly.

## Types of changes

+ Developer / backend feature enhancement

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards. 

## Prerelease Tasks

+ [ ] Ensure add-on compatibility - Moved to task on dev branch
+ [x] Fix https://github.com/gocodebox/lifterlms-advanced-videos/issues/46

### CODE REVIEW

**Comment by thomasplevy** [comment]
@eri-trabiccolo I think this is a good idea, am I solving a problem that doesn't exist?

File: includes/class-llms-assets.php [hunk 1]
```diff
@@ -0,0 +1,343 @@
...
+ */
+
+defined( 'ABSPATH' ) || exit;
+
+/**
+ * LLMS_Assets Class
+ *
+ * @since [version]
+ */
+class LLMS_Assets {
```
Comment (eri-trabiccolo) [inline includes/class-llms-assets.php:28]: do we plan to extend this?
If not, let's prevent it, no?
```suggestion
final class LLMS_Assets {
```

and of course `protected` methods do not make much sense in that case => `private`.

If, dunno, you're planning to extend this class in our add-ons then the `$scripts` and `$styles` properties, as well as the methods that manipulate them, shouldn't be static, right?
In this case `defaults` would be values passed during the instantiation of this class in class-lifterlms.php and assign the instance to a LifterLMS property, like `$session` and `$query`. What do you think?

Just considerations that, obviously you can totally skip <3

File: includes/assets/llms-assets-styles.php [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+return array(
+	'lifterlms-styles' => array(
+		'file_slug' => 'lifterlms',
+	),
+	'llms-iziModal'    => array(
+		'file_slug' => 'iziModal',
+		'path'      => 'assets/vendor/izimodal',
+		'version'   => '1.5.1',
+	),
+);
```
Comment (eri-trabiccolo) [inline includes/assets/llms-assets-styles.php:48]: question: the idea is to all our style assets definitions here, right?

File: includes/class-llms-assets.php [hunk 3]
```diff
@@ -0,0 +1,343 @@
...
+	 *
+	 * If the script has not yet been registered, it will be automatically registered.
+	 *
+	 * The script *must* be defined in one of the following places:
+	 *
+	 *   + The script definition list found at includes/assets/llms-assets-scripts.php
+	 *   + Added to the definition list via the `llms_get_script_asset_definitions` filter
+	 *   + Added "just in time" via the `llms_get_script_asset` filter.
+	 *
+	 * If the script is *not defined* it this function will return `false` because registration
```
Comment (eri-trabiccolo) [inline includes/class-llms-assets.php]:
```suggestion
	 * If the script is *not defined* this function will return `false` because registration
```

File: includes/class-llms-assets.php [hunk 4]
```diff
@@ -0,0 +1,343 @@
...
+	 *
+	 * If the stylesheet has not yet been registered, it will be automatically registered.
+	 *
+	 * The stylesheet *must* be defined in one of the following places:
+	 *
+	 *   + The stylesheet definition list found at includes/assets/llms-assets-styles.php
+	 *   + Added to the definition list via the `llms_get_style_asset_definitions` filter
+	 *   + Added "just in time" via the `llms_get_style_asset` filter.
+	 *
+	 * If the stylesheet is *not defined* it this function will return `false` because registration
```
Comment (eri-trabiccolo) [inline includes/class-llms-assets.php]:
```suggestion
	 * If the stylesheet is *not defined* this function will return `false` because registration
```

File: includes/class-llms-assets.php [hunk 5]
```diff
@@ -0,0 +1,343 @@
...
+	 */
+	protected static function get( $type, $handle ) {
+
+		$list  = self::get_definitions( $type );
+		$asset = isset( $list[ $handle ] ) ? $list[ $handle ] : false;
+
+		/**
+		 * Filter static asset data prior to preparing the definition
+		 *
+		 * The definition is "prepared" by merging it's data with the default data and preparing it's src.
```
Comment (eri-trabiccolo) [inline includes/class-llms-assets.php]:
```suggestion
		 * The definition is "prepared" by merging its data with the default data and preparing its src.
```

File: includes/class-llms-assets.php [hunk 6]
```diff
@@ -0,0 +1,343 @@
...
+	/**
+	 * Registers a defined script with WordPress
+	 *
+	 * The script *must* be defined in one of the following places:
+	 *
+	 *   + The script definition list found at includes/assets/llms-assets-scripts.php
+	 *   + Added to the definition list via the `llms_get_script_asset_definitions` filter
+	 *   + Added "just in time" via the `llms_get_script_asset` filter.
+	 *
+	 * If the script is *not defined* it this function will return `false`.
```
Comment (eri-trabiccolo) [inline includes/class-llms-assets.php]:
```suggestion
	 * If the script is *not defined* this function will return `false`.
```

File: includes/class-llms-assets.php [hunk 7]
```diff
@@ -0,0 +1,343 @@
...
+	 *
+	 * @since [version]
+	 *
+	 * @param string $handle The scripts handle.
```
Comment (eri-trabiccolo) [inline includes/class-llms-assets.php]:
```suggestion
	 * @param string $handle The script's handle.
```

File: includes/class-llms-assets.php [hunk 8]
```diff
@@ -0,0 +1,343 @@
...
+	 *
+	 * If the stylesheet has not yet been registered, it will be automatically registered.
+	 *
+	 * The stylesheet *must* be defined in one of the following places:
+	 *
+	 *   + The stylesheet definition list found at includes/assets/llms-assets-styles.php
+	 *   + Added to the definition list via the `llms_get_style_asset_definitions` filter
+	 *   + Added "just in time" via the `llms_get_style_asset` filter.
+	 *
+	 * If the stylesheet is *not defined* it this function will return `false`.
```
Comment (eri-trabiccolo) [inline includes/class-llms-assets.php]:
```suggestion
	 * If the stylesheet is *not defined* this function will return `false`.
```

File: includes/class-llms-assets.php [hunk 9]
```diff
@@ -0,0 +1,343 @@
...
+	 *
+	 * This method will also automatically adds RTL style data unless explicitly told not to do so.
```
Comment (eri-trabiccolo) [inline includes/class-llms-assets.php]:
```suggestion
	 * This method will also automatically add RTL style data unless explicitly told not to do so.
```

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
I only requested changes related to the docs.
Then I added a couple of comments.

File: includes/assets/llms-assets-styles.php (hunk 2 above)
Comment (thomasplevy) [reply includes/assets/llms-assets-styles.php:48]: Yes, I've started working on the list in a PR that I'll submit after we get this PR dialed in.

File: includes/class-llms-assets.php (hunk 1 above)
Comment (thomasplevy) [reply includes/class-llms-assets.php:28]: I do want this class to be extendable so that add-ons by us or 3rd parties can easily define their own assets and use these methods; should they wish.

My thinking was that the method by which add-ons would utilize this class would not be to extend the `$scripts` and `$styles` properties, but to instead utilize any number of the filters run by this class to define their own set of assets.

Though now that you mention this, maybe it would make sense to allow definitions to be added to these arrays.

Converting to a singleton as you're suggesting seems like a good way to do this. In that case I think everything should be converted from static (all the methods) as they'd be accessible via the singleton as you've suggested.

A developer could then extend the the class (I don't want to make it final with private methods) or they could use the filters. Depending on the complexity of the project or the number of assets one may make sense over the other.

An add-on with a single asset like a CSS file may just want to define it with a filter whereas a more complicated add-on may wish to extend the class, create their own asset list, and add them that way.

I think in this scenario we should probably create a `define()` method which would accept an array that would be added to the the relevant asset list.

Comment (eri-trabiccolo) [reply includes/class-llms-assets.php:28]: I actually wasn't suggesting to make it a singleton
I only wanted the LifterLMS class to instantiate its own and assign it to a property that can be referenced from other parts of the code.

I don't exactly remember the details but I remember that extending a singleton was not a good practice...

**Comment by thomasplevy** [comment]
Conversation moved from #1293:

https://github.com/gocodebox/lifterlms/pull/1293#discussion_r471475357

@eri-trabiccolo i-trabiccolo

> the static method enqueue_inline_script could be moved - and slightly modified - (of course for bw compatibility we'll maintain a wrapper here) into LLMS_Assets... what do you think?

@thomasplevy
> I was thinking about this too... All the inline stuff could be it's own class. I was thinking about making an LLMS_Assets_Inline class in favor of adding the inline stuff to the assets class. Actually, maybe it would make more sense to make inline asset-related functionality a trait that gets mixed into the asset class. I'm thinking mostly of keeping the number of methods per file smaller.

> What do you think?

File: includes/class-llms-assets.php (hunk 1 above)
Comment (thomasplevy) [reply includes/class-llms-assets.php:28]: Oh I see what you're saying. That would mean fewer rewritten tests. I'll update the PR in a bit

**Comment by thomasplevy** [comment]
@eri-trabiccolo this has gotten rather large and I don't want to plug anymore into it. Can you have another review and let me know if you see any other issues with the changes made per your last review.

I want to get this merged into dev and then we'll start doing checks against add-ons to ensure they're not using any deprecated methods or encountering issues as a result of these changes. We'll make sure all add-ons clear before merging to trunk.

Thanks

File: includes/llms.functions.core.php [hunk 10]
```diff
@@ -115,47 +115,21 @@ function llms_content( $content = '' ) {
...
  *
- * @param   string $function    name of the deprecated class or function
- * @param   string $version     version deprecation occurred
- * @param   string $replacement function to use in it's place (optional)
- * @return  void
- * @since   2.6.0
- * @version 3.6.0
+ * @since 2.6.0
+ * @since 3.6.0 Unknown.
+ * @since [version] Uses WP `_deprecated_function()` instead of duplicating it's logic.
```
Comment (eri-trabiccolo) [inline includes/llms.functions.core.php]:
```suggestion
 * @since [version] Uses WP `_deprecated_function()` instead of duplicating its logic.
```

File: includes/llms.functions.core.php [hunk 11]
```diff
@@ -115,47 +115,21 @@ function llms_content( $content = '' ) {
...
+ *
+ * @param string $function    Name of the deprecated function.
+ * @param string $version     LifterLMS version that deprecated the function.
+ * @param string $replacement Replacement function.
```
Comment (eri-trabiccolo) [inline includes/llms.functions.core.php]:
```suggestion
 * @param string $replacement Optional. Replacement function. Default is `null`.
```

File: tests/phpunit/unit-tests/functions/class-llms-test-functions-core.php [hunk 12]
```diff
@@ -11,6 +13,7 @@
  * @since 3.37.12 Fix errors thrown due to usage of `llms_section` instead of `section`.
  * @since 3.37.14 When testing `llms_get_post_parent_course()` added tests on other LLMS post types which are not instance of `LLMS_Post_Model`.
  * @since 4.2.0 Add tests for llms_get_completable_post_types() & llms_get_completable_taxonomies().
+ * @since [version] Add tests for `llms_deprecated_function()`
```
Comment (eri-trabiccolo) [inline tests/phpunit/unit-tests/functions/class-llms-test-functions-core.php]:
```suggestion
 * @since [version] Add tests for `llms_deprecated_function()`.
```

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
Minor doc cs fixes.
Last thing, just for completeness but we can work on it later:
Shall we use the same "deprecation" treatment for the following too?
(meaning trigger an error if WP_DEBUG):
https://github.com/gocodebox/lifterlms/blob/4.3.3/includes/functions/llms.functions.quiz.php#L122

I've just noticed that LifterLMS Labs, when using the Divi theme + compatibility layer active, triggers that in the builder.
I'm going to open an issue on that repo.

**Comment by thomasplevy** [comment]
> Minor doc cs fixes.
> Last thing, just for completeness but we can work on it later:
> Shall we use the same "deprecation" treatment for the following too?
> (meaning trigger an error if WP_DEBUG):
> https://github.com/gocodebox/lifterlms/blob/4.3.3/includes/functions/llms.functions.quiz.php#L122

We should actually use https://developer.wordpress.org/reference/functions/apply_filters_deprecated/ in favor of what the `llms_log()` + `apply_filters()`.

I'll open a new issue for that
