### PR TITLE
Automatically initialize payment gateways

### LINKED ISSUE #2074: Manual Payment Instructions do not appear on the order page
### Reproduction Steps

HS-189652
Go to the dashboard then LifterLMS >> Settings >> Checkout >> and enable the manual payment gateway. 
Make sure you add your payment instructions.
Try purchasing an access plan using the manual gateway method.
You'll have this kind of order page with no instruction on how to pay:
image

However, when I click the update payment method and select manual, and click pay now, the instruction now appears. See video:
https://www.loom.com/share/cafad648a5664c1bbdfc45f9acccbcaf

### Expected Behavior

I believe the instruction should be on the order page as well as long as it's a manual payment.

### Actual Behavior

Instruction not shown

### Error Messages / Logs

+ Include any relevant error messages or log files
```
N/A

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.9.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#889) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0
Course Catalog: Courses (#245) [[removed]/courses-2/]
Membership Catalog: Membership Catalog (#6) [[removed]/memberships/]
Student Dashboard: Dashboard (#8) [[removed]/dashboard/]
Checkout Page: Purchase (#7) [[removed]/purchase/]
Course Catalog Per Page: -1
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: %e3%82%b3%e3%83%bc%e3%82%b9
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: yes
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: hidden
Registration Email Confirmation: yes
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: PH
Currency: PHP
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 2


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.33
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.39


Theme
-------------------------------------------

Name: Kadence
Version: 1.1.15
Themeuri: https://www.kadencewp.com/kadence-theme/
Authoruri: https://www.kadencewp.com/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

AutomatorWP: 2.0.5
AutomatorWP - LifterLMS: 1.0.2
Code Snippets: 2.14.3
Conditional Menus: 1.2.0
Elementor: 3.5.6
Elementor Pro: 3.6.0
Font Awesome: 4.1.1
LifterLMS: 6.0.0
LifterLMS Advanced Quizzes: 2.0.1
LifterLMS Advanced Videos: 1.0.0-beta.18
LifterLMS Groups: 1.0.0-beta.19
LifterLMS Labs: 1.6.0
LifterLMS MailChimp Add-on: 3.2.0
LifterLMS Private Areas: 1.1.5
LifterLMS Social Learning: 1.5.0
LifterLMS Twilio: 1.1.2
Loco Translate: 2.6.1
User Switching: 1.5.8
WooCommerce: 6.3.1
WP Fusion: 3.38.46
WP Rollback: 1.7.1
Yoast SEO: 18.3


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS Groups: Yes
Twilio: Yes
LifterLMS MailChimp: Yes
LifterLMS Private Areas: Yes
LifterLMS Social Learning: Yes
Videos: Vimeo: Yes
Videos: Wistia: No
Videos: YouTube: Yes


Template Overrides
-------------------------------------------

course/lesson-preview.php (ver: 5.7.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)
course/syllabus.php (ver: 4.4.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)



```

</details>

This issue has be recreated:
+ [x ] Locally
+ [x] On a staging site
+ [x] On a production website
+ [] With only LifterLMS and a default theme

### PR DESCRIPTION
**Pull request by thomasplevy**
## Description

Fixes #2074

The issue is occurring because the `LLMS_Payment_Gateways` singleton isn't initialized until code accesses the `llms()->payment_gateways()` method. In the core plugin, when viewing an order, this doesn't happen until this hook:

https://github.com/gocodebox/lifterlms/blob/0a5e0a2c7cd522074f1988dd0979e3aa6289a0c3/templates/myaccount/view-order.php#L58

That means that the previous hook isn't accessible to payment gateway classes: https://github.com/gocodebox/lifterlms/blob/0a5e0a2c7cd522074f1988dd0979e3aa6289a0c3/templates/myaccount/view-order.php#L47

(Unless the core implements logic to load gateways before that hook)

This PR automatically loads all payment gateways at `init`, priority 10. This means that payment gateways that expect to be able to utilize this (or other) hooks, can do so.

The primary issue is here: https://github.com/gocodebox/lifterlms/blob/0a5e0a2c7cd522074f1988dd0979e3aa6289a0c3/includes/class.llms.gateway.manual.php#L52

## How has this been tested?

+ Manually

## Types of changes
+ Bugfix

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: class-lifterlms.php [hunk 1]
```diff
@@ -95,6 +96,7 @@ private function __construct() {
 		add_action( 'init', array( $this, 'processors' ), 5 );
 		add_action( 'init', array( $this, 'events' ), 5 );
 		add_action( 'init', array( $this, 'init_session' ), 6 ); // After table installation which happens at init 5.
+		add_action( 'init', array( $this, 'payment_gateways' ) );
```
Comment (pondermatic) [inline class-lifterlms.php:99]: Nitpicking here. Since the other action callbacks are registered with a specific priority, and sorted by that priority, it would be nice if the other two `init` callbacks were registered with an explicit priority of 10. Yes, we know the default is 10, but someone new to WordPress may not.

**Review by pondermatic — APPROVED** [review]

File: class-lifterlms.php (hunk 1 above)
Comment (thomasplevy) [reply class-lifterlms.php:99]: I'm going to leave this because this has no bearing on the bugfix.

It's more of a question of coding standards. And the question, to me, doesn't have much to do with hook callback priority so much as the usage of default values.

If we assume that new developers aren't familiar with WP function defaults we should probably assume that they're not familiar with our internal APIs defaults and then... should we ever use default values or should we always be explicitly declaring the values regardless of the ability to use defaults. And then should we *never code functions with default values*? 

The implications of making this kind of change for this reason are far-reaching. And don't concern this PR.
