### PR TITLE
Fix warning for themes without sidebar.php template

### LINKED ISSUE #2488: `get_sidebar` deprecation warning when using FSE theme
### Reproduction Steps

1. Install any FSE theme (other than Sky-Pilot)
2. Go to the Course Catalog or `/courses` page

### Expected Behavior

Should see the course catalog/archive.

### Actual Behavior

Shows a deprecated warning under courses loop

### Error Messages / Logs

*File Theme without sidebar.php is <strong>deprecated</strong> since version 3.0.0 with no alternative available. Please include a sidebar.php template in your theme.*

From `lifterlms/templates/global/sidebar.php`

### System and Environment Information

Any FSE theme
LifterLMS plugin

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

All

### PR DESCRIPTION
**Pull request by seothemes**
## Description

Fixes warning for themes without sidebar.php template.

Fixes #2488

## How has this been tested?

Manually

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] This PR requires and contains at least one changelog file.
- [ ] My code has been tested.
- [ ] My code passes all existing automated tests.
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: templates/global/sidebar.php [hunk 1]
```diff
@@ -5,9 +5,12 @@
...
  * @since Unknown
- * @version Unknown
+ * @since [version] Fix warning for themes without sidebar.php template.
+ * @version [version]
  */
 
 defined( 'ABSPATH' ) || exit;
 
-get_sidebar( 'llms_shop' );
+if ( ABSPATH . WPINC . '/theme-compat/sidebar.php' !== locate_template( array( 'sidebar-llms_shop', 'sidebar.php' ) ) ) {
```
Comment (eri-trabiccolo) [inline templates/global/sidebar.php]:
```suggestion
if ( ABSPATH . WPINC . '/theme-compat/sidebar.php' !== locate_template( array( 'sidebar-llms_shop.php', 'sidebar.php' ) ) ) {
```

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
Shall we limit the change for fse themes only?
I guess so, can you?

File: templates/global/sidebar.php [hunk 2]
```diff
@@ -5,9 +5,18 @@
  * @package LifterLMS/Templates
  *
  * @since Unknown
- * @version Unknown
+ * @since [version] Fix warning for themes without sidebar.php template.
```
Comment (eri-trabiccolo) [inline templates/global/sidebar.php]:
```suggestion
 * @since [version] Don't include WordPress default sidebar.php template when using a block theme.
```

File: .changelogs/fix-sidebar-fse.yml [hunk 3]
```diff
@@ -0,0 +1,5 @@
+significance: patch
+type: fixed
+links:
+  - "#2488"
+entry: Fixed warning for themes without sidebar.php template.
```
Comment (eri-trabiccolo) [inline .changelogs/fix-sidebar-fse.yml]:
```suggestion
entry: Don't include WordPress default sidebar.php template when using a block theme.
```

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
what do you think?

**Review by eri-trabiccolo — APPROVED** [review]
